import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      value = value?.[k];
    }
    
    let result = value || key;
    
    // Simple interpolation
    if (params && typeof result === 'string') {
      Object.keys(params).forEach(param => {
        result = result.replace(new RegExp(`{{${param}}}`, 'g'), String(params[param]));
      });
    }
    
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  pt: {
    common: {
      back: 'Voltar',
      goodbye: 'Até breve!',
      loading: 'A carregar...',
      error: 'Erro',
      success: 'Sucesso',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      save: 'Guardar',
      delete: 'Eliminar',
      edit: 'Editar',
      close: 'Fechar',
      yes: 'Sim',
      no: 'Não',
      or: 'ou',
      and: 'e',
      days: 'dias',
      day: 'dia',
      hours: 'horas',
      minutes: 'minutos',
      seconds: 'segundos',
    },
    loadingStates: {
      title: 'Loading States',
      description: 'Exemplos de spinners, skeleton loaders e overlays',
      overlayTitle: 'Loading Overlay',
      showOverlay: 'Mostrar Overlay (3 segundos)',
      processing: 'Processando dados...',
    },
    trial: {
      activeMessage: 'Free Trial ativo - {{days}} dias restantes com acesso total ao plano Standard',
      expiringWarning: 'Free Trial expira em {{days}} dias! Faça upgrade para continuar',
      upgradeNow: 'Fazer Upgrade',
      expired: {
        title: 'Free Trial Expirado',
        description: 'O seu período de teste de 10 dias terminou. Para continuar a usar todas as funcionalidades, escolha um plano.',
        whatHappensNext: 'O que acontece agora?',
        noAccess: 'Sem acesso a funcionalidades premium',
        dataPreserved: 'Os seus dados estão preservados',
        chooseAPlan: 'Escolha um plano para continuar',
        maybeLater: 'Talvez Depois',
        viewPlans: 'Ver Planos',
      },
    },
    limits: {
      exceeded: {
        stores: {
          title: 'Limite de Lojas Atingido',
          description: 'Tem {{current}} lojas mas o seu plano permite apenas {{max}}. Remova lojas em excesso ou faça upgrade.',
        },
        campaigns: {
          title: 'Limite de Campanhas Atingido',
          description: 'Tem {{current}} campanhas mas o seu plano permite apenas {{max}}. Remova campanhas em excesso ou faça upgrade.',
        },
        howToFix: 'Como resolver:',
        option1: 'Remova recursos em excesso',
        option2: 'Faça upgrade para um plano superior',
        cancel: 'Cancelar',
        upgradePlan: 'Fazer Upgrade',
      },
    },
    subscription: {
      readOnlyTitle: 'Modo de Leitura',
      subscriptionExpired: 'A sua assinatura {{planName}} expirou.',
      daysUntilSuspension: 'Tem {{days}} dias para reativar antes da suspensão.',
      readOnlyCapabilities: 'Em modo de leitura pode:',
      viewData: 'Visualizar os seus dados',
      exportReports: 'Exportar relatórios',
      cannotCreateCampaigns: 'Criar ou editar campanhas',
      cannotSyncData: 'Sincronizar novos dados',
      reactivateSubscription: 'Reativar Assinatura',
      bannerExpiredTitle: 'Assinatura {{planName}} Expirada',
      bannerExpiredDesc: 'Acesso em modo leitura. Faltam {{days}} dias até à suspensão da conta.',
      bannerExpiredDescNoDate: 'Acesso em modo leitura. Reative a sua assinatura para continuar.',
      reactivateNow: 'Reativar Agora',
      bannerSuspendedTitle: 'Conta Suspensa',
      bannerSuspendedDesc: 'A sua conta está suspensa. Em {{days}} dias, os seus dados serão arquivados permanentemente (RGPD).',
      bannerSuspendedDescNoDate: 'A sua conta está suspensa. Reative para recuperar o acesso.',
      recoverAccount: 'Recuperar Conta',
      bannerArchivedTitle: 'Conta Arquivada',
      bannerArchivedDesc: 'Os seus dados foram anonimizados. Para restaurar o acesso, contacte o suporte ou inicie uma nova assinatura.',
      newPlan: 'Novo Plano',
      upsellStoreTitle: 'Limite de Lojas Atingido',
      upsellStoreDesc: 'Está a usar {{current}}/{{limit}} lojas permitidas no seu plano.',
      upsellCampaignTitle: 'Limite de Campanhas Atingido',
      upsellCampaignDesc: 'Está a usar {{current}}/{{limit}} campanhas permitidas no seu plano.',
      unlockWithUpgrade: 'Desbloqueie com o upgrade:',
      unlimitedStores: 'Lojas ilimitadas',
      automaticSync: 'Sincronização automática',
      multiStoreManagement: 'Gestão multi-loja',
      prioritySupport: 'Suporte prioritário',
      unlimitedCampaigns: 'Campanhas ilimitadas',
      advancedAutomation: 'Automação avançada',
      performanceAnalysis: 'Análise de performance',
      detailedROI: 'ROI detalhado',
      upgradeTip: 'Faça upgrade agora e continue a crescer sem limites',
      maybeLater: 'Talvez Depois',
      viewPlans: 'Ver Planos',
      storeLimitReached: 'Limite Atingido',
      upgradeRequired: 'Upgrade Necessário',
    },
    validation: {
      required: 'Campo obrigatório',
      invalidEmail: 'Endereço de email inválido',
      emailTooLong: 'Email deve ter menos de 255 caracteres',
      passwordMinLength: 'A palavra-passe deve ter pelo menos 8 caracteres',
      passwordMaxLength: 'A palavra-passe deve ter menos de 128 caracteres',
      nameTooShort: 'O nome não pode estar vazio',
      nameTooLong: 'O nome deve ter menos de 100 caracteres',
      companyNameTooLong: 'O nome da empresa deve ter menos de 200 caracteres',
      storeNameRequired: 'O nome da loja é obrigatório',
      storeNameTooLong: 'O nome da loja é demasiado longo',
      accessTokenRequired: 'O token de acesso é obrigatório',
      accessTokenTooLong: 'O token de acesso é demasiado longo',
      invalidAction: 'Ação inválida',
      invalidCampaignId: 'ID de campanha inválido',
      campaignNameTooLong: 'O nome da campanha deve ter menos de 200 caracteres',
      budgetMustBePositive: 'O orçamento deve ser positivo',
      statusMustBeValid: 'O estado deve ser ATIVO ou PAUSADO',
    },
    nav: {
      whatIsIt: 'O que é',
      features: 'Funcionalidades',
      pricing: 'Preços',
      faq: 'FAQ',
    },
    header: {
      login: 'Entrar',
      startFree: 'Começar Grátis',
      getStarted: 'Começar',
    },
    landing: {
      hero: {
        title1: 'Automatize as suas',
        title2: 'Campanhas de Facebook',
        subtitle: 'A sua plataforma inteligente para cálculo automático de métricas e recomendações de ação.',
        benefit1: 'Calcula métricas automaticamente',
        benefit2: 'CPC, ROAS, CPA, Margem de Lucro em tempo real',
        benefit3: 'Recomendações inteligentes: Parar, Escalar, Manter',
        ctaPrimary: 'Começar Grátis por 10 Dias',
        ctaSecondary: 'O que o Sheet Tools faz por si',
      },
      whatIsIt: {
        title: 'Análise Inteligente de Campanhas',
        subtitle: 'O Sheet Tools revoluciona a forma como gere as suas campanhas de Facebook Ads. A nossa plataforma analisa automaticamente as suas métricas e oferece recomendações precisas para maximizar os seus resultados.',
        smartAnalysis: {
          title: 'Análise Inteligente',
          description: 'Calcula automaticamente CPC, ROAS, COGS, CPA, Margem de Lucro e outras métricas essenciais.',
        },
        decisionAutomation: {
          title: 'Automação de Decisões',
          description: 'Recomendações automáticas: parar campanhas ruins, escalar as rentáveis, manter as estáveis.',
        },
      },
      features: {
        title: 'Funcionalidades que fazem a diferença',
        subtitle: 'Tudo o que precisa para otimizar as suas campanhas numa só plataforma',
        integration: {
          title: 'Integração Facebook Ads',
          description: 'Ligue-se diretamente às suas campanhas para análise em tempo real',
        },
        metrics: {
          title: 'Métricas Automáticas',
          description: 'ROAS, CPC, CPA, CTR, Taxa de Conversão calculados automaticamente',
        },
        ai: {
          title: 'IA para Decisões',
          description: 'Algoritmos inteligentes sugerem as melhores ações para cada campanha',
        },
        automation: {
          title: 'Automação Completa',
          description: 'Poupe horas de análise manual com automação inteligente',
        },
        profit: {
          title: 'Análise de Lucros',
          description: 'Cálculo preciso de COGS, Margem de Lucro e ROI real',
        },
        secure: {
          title: 'Dados Seguros',
          description: 'Conexão segura via OAuth, os seus dados sempre protegidos',
        },
      },
      pricing: {
        title: 'Escolha o Seu Plano Perfeito',
        subtitle: 'Planos simples e transparentes para automatizar as suas campanhas do Facebook',
        popular: 'Mais Popular',
        choosePlan: 'Escolher Plano',
        monthly: 'Mensal',
        annual: 'Anual',
        save3Months: 'POUPE 3 MESES',
        basic: {
          name: 'Basic',
          price: '€14.99',
          perMonth: '/mês',
          description: 'Profit Sheet (1 loja, 15 campanhas)',
          feature1: 'Daily ROAS (Automático em todos)',
          feature2: 'Profit Sheet',
          feature3: '1 loja',
          feature4: '15 campanhas',
          annualOriginal: '179,88 €',
          annualPrice: '€134.91',
          perYear: '/ano',
          annualSavings: 'Poupe 44,97 € (3 meses grátis)',
        },
        standard: {
          name: 'Standard',
          price: '€34.99',
          perMonth: '/mês',
          description: 'Profit Sheet + Campanhas + Cotação (2 lojas, 40 campanhas)',
          feature1: 'Daily ROAS (Automático em todos)',
          feature2: 'Profit Sheet',
          feature3: 'Campanhas',
          feature4: 'Cotação',
          feature5: '2 lojas',
          feature6: '40 campanhas',
          annualOriginal: '419,88 €',
          annualPrice: '€314.91',
          perYear: '/ano',
          annualSavings: 'Poupe 104,97 € (3 meses grátis)',
        },
        expert: {
          name: 'Expert',
          price: '€49.99',
          perMonth: '/mês',
          description: 'Standard + Product Research (4 lojas, campanhas ilimitadas)',
          feature1: 'Daily ROAS (Automático em todos)',
          feature2: 'Profit Sheet',
          feature3: 'Campanhas',
          feature4: 'Cotação',
          feature5: 'Product Research',
          feature6: '4 lojas',
          feature7: 'Campanhas ilimitadas',
          annualOriginal: '599,88 €',
          annualPrice: '€449.91',
          perYear: '/ano',
          annualSavings: 'Poupe 149,97 € (3 meses grátis)',
        },
        business: {
          name: 'Business',
          price: 'Customizado',
          perMonth: '',
          description: 'Solução empresarial totalmente personalizada',
          feature1: 'Tudo do Expert',
          feature2: 'Lojas ilimitadas',
          feature3: 'Suporte dedicado',
          feature4: 'Onboarding personalizado',
          feature5: 'Funcionalidades customizadas',
          feature6: 'Integrações sob demanda',
          contactUs: 'Contacte-nos',
        },
        featureComparison: {
          title: 'Comparação de Funcionalidades',
          feature: 'Funcionalidade',
          note: 'Nota: Daily ROAS é automático em todos os planos',
          dailyRoas: 'Daily ROAS (Automático)',
          profitSheet: 'Profit Sheet',
          quotation: 'Cotação',
          campaigns: 'Campanhas',
          productResearch: 'Product Research',
          prioritySupport: 'Suporte Prioritário',
          completeHistory: 'Histórico Completo',
        },
      },
      faq: {
        title: 'Perguntas Frequentes',
        subtitle: 'Esclareça as suas dúvidas sobre o Sheet Tools',
      },
      cta: {
        title: 'Pronto para automatizar o seu ROAS?',
        description: 'Junte-se a centenas de empresas que já poupam 10+ horas semanais e aumentaram os seus lucros em 23%',
        button: 'Começar Agora - 10 Dias Grátis',
      },
    },
    faq: {
      title: 'Perguntas Frequentes',
      subtitle: 'Esclareça as suas dúvidas sobre o Sheet Tools',
      q1: {
        question: 'Como funciona o cálculo automático de métricas?',
        answer: 'O Sheet Tools liga-se diretamente às suas campanhas de Facebook Ads e calcula automaticamente todas as métricas essenciais como ROAS, CPC, CPA, Margem de Lucro, BER e muito mais. Os dados são atualizados em tempo real.',
      },
      q2: {
        question: 'Que tipo de recomendações a plataforma oferece?',
        answer: 'Com base em regras de performance avançadas, a plataforma sugere automaticamente se deve PARAR uma campanha de baixo desempenho, ESCALAR uma campanha rentável, MANTER uma campanha estável ou REDUZIR quando necessário.',
      },
      q3: {
        question: 'Preciso de conhecimentos técnicos para usar?',
        answer: 'Não! O Sheet Tools foi desenhado para ser intuitivo. Basta ligar as suas campanhas e a plataforma faz todo o trabalho pesado de análise e recomendações automaticamente.',
      },
      q4: {
        question: 'Como funciona o período de teste?',
        answer: '10 dias completamente grátis com acesso a todas as funcionalidades. Não é necessário cartão de crédito.',
      },
      q5: {
        question: 'Posso cancelar a qualquer momento?',
        answer: 'Sim! Não há compromisso. Pode cancelar sempre que quiser e continuar a usar até ao final do período pago.',
      },
    },
    footer: {
      quickLinks: 'Links Rápidos',
      home: 'Início',
      features: 'Funcionalidades',
      pricing: 'Preços',
      faq: 'FAQ',
      legal: 'Legal',
      termsOfService: 'Termos de Serviço',
      privacyPolicy: 'Política de Privacidade',
      contact: 'Contacto',
      copyright: '© 2025 Sheet Tools. Todos os direitos reservados.',
    },
    stats: {
      hours: 'Horas poupadas por semana',
      roi: 'Aumento médio de ROI',
      companies: 'Empresas que confiam em nós',
    },
    cta: {
      title: 'Pronto para automatizar o seu ROAS?',
      description: 'Junte-se a centenas de empresas que já poupam 10+ horas semanais e aumentaram os seus lucros em 23%',
      button: 'Começar Agora - 10 Dias Grátis',
    },
    sidebar: {
      dashboard: 'Dashboard',
      campaigns: 'Campanhas',
      products: 'Produtos',
      settings: 'Configurações',
      premium: 'Premium',
      premiumDesc: 'Desbloqueie recursos avançados',
      upgrade: 'Fazer Upgrade',
      logout: 'Sair',
      dailyRoas: 'Daily ROAS',
      profitSheet: 'Profit Sheet',
      integrations: 'Integrações',
      moreOptions: 'Mais opções',
      support: 'Suporte',
      adminPanel: 'Painel Admin',
      terms: 'Termos de Serviço',
      privacy: 'Política de Privacidade',
    },
    onboarding: {
      title: 'Bem-vindo ao Sheet-Tools!',
      subtitle: 'Configure a sua conta em 3 passos simples',
      step1Title: 'Ligar Facebook Ads',
      step1Desc: 'Ligue a sua conta do Facebook Ads para importar campanhas',
      step2Title: 'Ligar Shopify',
      step2Desc: 'Sincronize os seus produtos e vendas do Shopify',
      step3Title: 'Adicionar Produtos',
      step3Desc: 'Configure os seus produtos para análise de ROAS',
      startButton: 'Iniciar Configuração',
      skipButton: 'Saltar por agora',
      setupTitle: 'Configure a sua Conta',
      stepsCompleted: 'passos concluídos',
      step: 'Passo',
      completed: 'Concluído',
      clickToSetup: 'Clique para configurar',
    },
    dashboard: {
      title: 'Painel de Controlo',
      overview: 'Visão Geral',
      welcome: 'Bem-vindo ao Sheet-Tools! Aqui está uma visão geral das suas métricas.',
      of: 'de',
      avgRoas: 'ROAS Médio',
      avgCpa: 'CPA Médio',
      totalSpent: 'Total Gasto',
      activeCampaigns: 'Campanhas Ativas',
      conversions: 'Conversões',
      activeUsers: 'Utilizadores Ativos',
      monthlyRevenue: 'Receita Mensal',
      conversionRate: 'Taxa de Conversão',
      recentCampaigns: 'Campanhas Recentes',
      nextSteps: 'Próximos Passos',
      connectFacebook: 'Ligar Facebook Ads',
      connectFacebookDesc: 'Importe as suas campanhas automaticamente',
      integrateShopify: 'Integrar Shopify',
      integrateShopifyDesc: 'Sincronize produtos e vendas',
      connect: 'Ligar',
      integrate: 'Integrar',
      loading: 'A carregar...',
    },
    campaigns: {
      title: 'Campanhas',
      notConnected: 'Facebook Ads não ligado',
      notConnectedDesc: 'Para visualizar e gerir as suas campanhas, precisa de ligar a sua conta do Facebook Ads.',
      goToSettings: 'Ir para Definições',
      totalSpent: 'Total Gasto',
      totalRevenue: 'Receita Total',
      avgRoas: 'ROAS Médio',
      activeCampaigns: 'Campanhas Ativas',
      search: 'Pesquisar campanhas...',
      filterAll: 'Todas',
      filterActive: 'Ativa',
      filterPaused: 'Pausada',
      filterArchived: 'Arquivada',
      refresh: 'Atualizar',
      noCampaigns: 'Nenhuma campanha encontrada.',
      spent: 'Gasto',
      revenue: 'Receita',
      roas: 'ROAS',
      cpa: 'CPA',
      conversions: 'Conversões',
      impressions: 'Impressões',
      loading: 'A carregar campanhas...',
    },
    metaDashboard: {
      title: 'Ads Manager',
      loading: 'A carregar Meta Dashboard...',
      connectTitle: 'Conecte a sua conta Meta',
      connectDesc: 'Para aceder ao Meta Ads Dashboard, precisa de conectar a sua conta Meta primeiro.',
      goToSettings: 'Ir para Definições',
      connectedBadge: 'Ligado à Meta',
      adAccount: 'Conta de Anúncios',
      selectAccount: 'Selecionar conta',
      period: 'Período',
      last7Days: 'Últimos 7 dias',
      last30Days: 'Últimos 30 dias',
      last90Days: 'Últimos 90 dias',
      thisMonth: 'Este mês',
      today: 'Hoje',
      custom: 'Personalizado',
      refresh: 'Atualizar',
      totalSpent: 'Montante Gasto',
      avgCPC: 'CPC Médio',
      cpm: 'CPM',
      ctr: 'CTR',
      results: 'Resultados',
      impressions: 'Impressões',
      spendChart: 'Gasto por Campanha',
      cpcChart: 'CPC por Campanha',
      searchPlaceholder: 'Pesquisar campanhas por nome...',
      filterAll: 'Todos',
      filterActive: 'Ativas',
      filterInactive: 'Inativas',
      name: 'Nome',
      status: 'Estado',
      budget: 'Orçamento',
      reach: 'Alcance',
      linkClicks: 'Cliques na Ligação',
      landingPageViews: 'Visualização na Página',
      costPerResult: 'Custo por Resultado',
      costPerLandingPageView: 'Custo por visualização da página',
      roas: 'ROAS',
      spent: 'Montante Gasto',
      cpc: 'CPC',
      startDate: 'Data Início',
      actions: 'Ações',
      noCampaigns: 'Nenhuma campanha encontrada.',
      pausedSuccess: 'Campanha desligada',
      pausedDesc: 'A campanha foi desligada com sucesso.',
      activatedSuccess: 'Campanha ligada',
      activatedDesc: 'A campanha foi ligada com sucesso.',
      deletedSuccess: 'Campanha eliminada',
      deletedDesc: 'A campanha foi eliminada com sucesso.',
      detailsTitle: 'Detalhes da Campanha',
      detailsDesc: 'Informação completa sobre a campanha selecionada',
      clicks: 'Cliques',
      spend: 'Gasto',
      createdOn: 'Criado em',
      dateRange: 'Intervalo de Datas',
      selectRange: 'Selecionar intervalo',
      applyFilter: 'Aplicar Filtro',
      confirmDeleteTitle: 'Confirmar Eliminação',
      confirmDeleteDesc: 'Tem a certeza de que deseja eliminar esta campanha? Esta ação não pode ser revertida.',
      confirmDelete: 'Sim, Eliminar',
      confirmPauseTitle: 'Confirmar Desligar',
      confirmPauseDesc: 'Tem a certeza de que deseja desligar esta campanha?',
      confirmPause: 'Sim, Desligar',
      confirmActivateTitle: 'Confirmar Ligar',
      confirmActivateDesc: 'Tem a certeza de que deseja ligar esta campanha?',
      confirmActivate: 'Sim, Ligar',
      cancel: 'Cancelar',
      columns: 'Colunas',
      viewPredefined: 'Vista Pré-definida',
      viewCustom: 'Vista Personalizada',
      selectColumns: 'Selecionar colunas a mostrar',
      resetColumns: 'Repor Pré-definição',
      applyColumns: 'Aplicar',
      connectFacebookDesc: 'Conecte o Facebook Ads para começar',
      errorLoadingAccounts: 'Erro ao carregar contas',
      noAccountsFound: 'Nenhuma conta encontrada',
      noAccountsFoundDesc: 'Não foram encontradas contas de anúncios na sua conta Meta.',
      unknownErrorLoadingAccounts: 'Erro desconhecido ao carregar contas',
      errorLoadingCampaigns: 'Erro ao carregar campanhas',
      unknownErrorLoadingCampaigns: 'Erro desconhecido ao carregar campanhas',
      error: 'Erro',
      invalidCampaignId: 'ID da campanha inválido',
      errorPausing: 'Erro ao pausar',
      unknownError: 'Erro desconhecido',
      errorPausingCampaign: 'Erro ao pausar campanha',
      errorActivating: 'Erro ao ativar',
      errorActivatingCampaign: 'Erro ao ativar campanha',
      errorDeleting: 'Erro ao eliminar',
      errorDeletingCampaign: 'Erro ao eliminar campanha',
      pause: 'Pausar',
      activate: 'Ativar',
      customize: 'Personalizar',
      subtitle: 'Gestão de Campanhas do Facebook Ads',
      campaignsTitle: 'Campanhas',
      perDay: '/dia',
      total: 'total',
      removeCampaign: 'Remover Campanha',
      active: 'Active',
      paused: 'Paused',
      editCampaign: 'Editar Campanha',
      campaignName: 'Nome da Campanha',
      campaignNamePlaceholder: 'Nome da campanha',
      dailyBudget: 'Orçamento Diário',
      dailyBudgetDesc: 'Deixe vazio se usar orçamento total',
      lifetimeBudget: 'Orçamento Total',
      lifetimeBudgetDesc: 'Deixe vazio se usar orçamento diário',
      schedule: 'Horários',
      startTime: 'Data/Hora de Início',
      stopTime: 'Data/Hora de Fim',
      saveChanges: 'Salvar Alterações',
      updatedSuccess: 'Campanha atualizada',
      updatedDesc: 'A campanha foi atualizada com sucesso.',
      errorUpdating: 'Erro ao atualizar',
      errorUpdatingCampaign: 'Erro ao atualizar campanha',
      noChanges: 'Sem alterações',
      noChangesDesc: 'Não foram feitas alterações para salvar.',
      viewDetails: 'Ver detalhes',
      changeImage: 'Alterar Imagem',
      uploadImage: 'Carregar Nova Imagem',
      currentImage: 'Imagem Atual',
      imageUpdated: 'Imagem atualizada',
      imageUpdatedDesc: 'A imagem da campanha foi atualizada com sucesso.',
      errorUpdatingImage: 'Erro ao atualizar imagem',
      noImage: 'Nenhuma imagem disponível',
      imageUploadDesc: 'Formatos suportados: JPG, PNG, GIF. Tamanho máximo: 5MB',
      campaign: 'Campanha',
      adSets: 'Ad Sets',
      ads: 'Anúncios',
      noAdSets: 'Nenhum ad set encontrado',
      noAds: 'Nenhum anúncio encontrado',
      adSetName: 'Nome do Ad Set',
      optimizationGoal: 'Objetivo de Otimização',
      optimizationGoalPlaceholder: 'Ex: LINK_CLICKS, CONVERSIONS',
      saveAdSet: 'Salvar Ad Set',
      adSetUpdated: 'Ad Set atualizado',
      adSetUpdatedDesc: 'O ad set foi atualizado com sucesso.',
      errorUpdatingAdSet: 'Erro ao atualizar ad set',
      errorLoadingAdSets: 'Erro ao carregar ad sets',
      adName: 'Nome do Anúncio',
      adTitle: 'Título do Anúncio',
      adTitlePlaceholder: 'Título do anúncio',
      adBody: 'Texto do Anúncio',
      adBodyPlaceholder: 'Texto do anúncio',
      saveAd: 'Salvar Anúncio',
      adUpdated: 'Anúncio atualizado',
      adUpdatedDesc: 'O anúncio foi atualizado com sucesso.',
      errorUpdatingAd: 'Erro ao atualizar anúncio',
      currency: '€',
      currencySymbol: '(€)',
      placeholderBudget: '0.00',
      billingEvent: 'Evento de Faturamento',
      billingEventPlaceholder: 'Ex: IMPRESSIONS, LINK_CLICKS',
    },
      storeSelector: {
        selectStore: 'Selecionar loja',
        allStores: 'Todas as Lojas',
      },
      products: {
        title: 'Gestão de Produtos',
        subtitle: 'Gestão de Produtos e Inventário',
        totalProducts: 'Total de Produtos',
        totalRevenue: 'Receita Total',
        unitsSold: 'Unidades Vendidas',
        avgMargin: 'Margem Média',
        search: 'Pesquisar produtos por nome ou SKU...',
        allStores: 'Todas as Lojas',
        allPeriods: 'Todos os períodos',
        today: 'Hoje',
        total: 'Total',
        yesterday: 'Ontem',
        last7Days: 'Últimos 7 dias',
        last14Days: 'Últimos 14 dias',
        last30Days: 'Últimos 30 dias',
        last90Days: 'Últimos 90 dias',
        customize: 'Personalizar',
        exportSold: 'Exportar Vendidos',
        newProduct: 'Novo Produto',
        addProduct: 'Adicionar Novo Produto',
        addProductDesc: 'Preencha os detalhes do produto para adicionar ao seu catálogo.',
        productName: 'Nome do Produto',
        sku: 'SKU (Opcional)',
        costPrice: 'Preço de Custo (€)',
        sellingPrice: 'Preço de Venda (€)',
        supplierQuote: 'Cotação (Fornecedor)',
        cancel: 'Cancelar',
        add: 'Adicionar Produto',
        noProducts: 'Nenhum produto encontrado',
        noProductsDesc: 'Adicione o seu primeiro produto para começar',
        adjustSearch: 'Tente ajustar a pesquisa',
        sold: 'Vendidos',
        margin: 'Margem',
        avgPrice: 'Preço Médio',
        profit: 'Profit',
        edit: 'Editar',
        loading: 'A carregar produtos...',
        syncing: 'A sincronizar...',
        syncShopify: 'Sincronizar Shopify',
        connectShopifyToStart: 'Conecte sua loja Shopify para começar',
        noProductsSold: 'Nenhum produto vendido',
        syncSalesToSeeProducts: 'Sincronize as vendas da sua loja Shopify para ver os produtos vendidos',
        syncingSales: 'A sincronizar vendas...',
        syncShopifySales: 'Sincronizar Vendas Shopify',
        noProductsToExport: 'Não há produtos com vendas para exportar',
        exportCompleted: 'Exportação concluída',
        exportSuccess: '{{count}} produtos exportados com sucesso',
        exportFileName: 'produtos_vendidos',
        exportHeaders: {
          productName: 'Nome do Produto',
          sku: 'SKU',
          costPrice: 'Preço de Fornecedor',
          sellingPrice: 'Preço de Venda',
          quantitySold: 'Unidades Vendidas',
          totalRevenue: 'Receita Total',
          profitMargin: 'Margem de Lucro (%)',
          createdAt: 'Data de Criação',
        },
      },
      productResearch: {
        title: 'Pesquisa de Produtos Virais',
        subtitle: 'Descobre produtos virais através da Facebook Ads Library',
        underDevelopment: 'Em Desenvolvimento',
        comingSoon: 'Esta funcionalidade estará disponível em breve',
        description: 'Estamos a trabalhar para trazer-te a melhor experiência de pesquisa de produtos virais através da Facebook Ads Library.',
        feature1: '🔍 Facebook Ads Library',
        feature2: '📊 Análise Avançada',
        feature3: '🎯 Filtros Personalizados',
        backToDashboard: 'Voltar ao Dashboard',
        filters: 'Filtros de Pesquisa',
        filtersDesc: 'Define os critérios para encontrar anúncios',
        customToken: 'Usar Token Personalizado',
        recommended: 'Recomendado',
        activated: 'Ativado',
        deactivated: 'Desativado',
        searchTerm: 'Termo de Pesquisa',
        searchPlaceholder: 'Ex: wireless earbuds, fitness tracker, skincare...',
        search: 'Pesquisar',
        searching: 'A pesquisar...',
        period: 'Período',
        allTime: 'Últimos 12 meses',
        last3Months: 'Últimos 3 meses',
        lastMonth: 'Último mês',
        minReach: 'Alcance Mínimo (impressões)',
        minDays: 'Dias Ativos (mínimo)',
        maxDays: 'Dias Ativos (máximo)',
        countries: 'Países UK/UE',
        selectAll: 'Selecionar Todos',
        clear: 'Limpar',
        adType: 'Tipo de Anúncio',
        image: 'Imagem',
        video: 'Vídeo',
        carousel: 'Carrossel',
        link: 'Link',
        noticeTitle: 'Facebook Ads Library - Foco UK/UE',
        noticeDesc: 'Esta ferramenta pesquisa anúncios comerciais ativos entregues no Reino Unido e União Europeia.',
        noticeTip: '💡 Dica: Usa termos de pesquisa em inglês para melhores resultados (ex: "wireless earbuds" em vez de "auriculares sem fios")',
        statsTitle: 'Estatísticas da Pesquisa',
        totalAds: 'Total de Anúncios',
        avgImpressions: 'Média de Impressões',
        avgDaysActive: 'Média de Dias Ativos',
        topCountry: 'País Principal',
        mostCommonAdType: 'Tipo Mais Comum',
        resultsTitle: 'Anúncios Encontrados',
        noResults: 'Nenhum anúncio encontrado com os critérios selecionados.',
        tryAdjust: 'Tenta ajustar os filtros ou usar termos de pesquisa diferentes.',
        viewFullAd: 'Ver Anúncio Completo',
        active: 'Ativo',
        inactive: 'Inativo',
        reach: 'Alcance',
        activeFor: 'Ativo há',
        start: 'Início',
        selectedCountries: 'países selecionados',
        selectedCountry: 'país selecionado',
        days: 'dias',
      },
      profitSheet: {
        title: 'Profit Sheet',
        subtitle: 'Análise de Lucros e Gastos',
        selectStore: 'Selecionar Loja e Conta de Anúncios',
        selectStoreDesc: 'Escolhe a loja Shopify e a conta de Facebook Ads para visualizar o Profit Sheet',
        shopifyStore: 'Loja Shopify',
        adAccount: 'Ad Account (Conta de Anúncios)',
        selectShopify: 'Selecionar loja Shopify',
        selectAdAccount: 'Selecionar Ad Account',
        selected: 'Selecionada',
        confirmSelection: 'Confirmar Seleção',
        changeSelection: 'Alterar Seleção',
        totalRevenue: 'Revenue Total',
        totalProfit: 'Profit Total',
        totalAdSpend: 'Ad Spend Total',
        avgRoas: 'ROAS Médio',
        totalMarginEur: 'Margem Total (€)',
        avgMarginPerc: 'Margem Média (%)',
        date: 'Data',
        revenue: 'Revenue',
        cog: 'COG',
        adSpend: 'Ad Spend',
        others: 'Outros',
        refunds: 'Refunds',
        fee: 'Taxa',
        profit: 'Profit',
        roas: 'ROAS',
        profitMargin: 'P%',
        cogPercentage: 'COG%',
        actions: 'Ações',
        loading: 'A carregar dados...',
        noData: 'Nenhum dado disponível',
        savedSuccessfully: 'Os valores foram atualizados',
        allPeriods: 'Todos os períodos',
        today: 'Hoje',
        total: 'Total',
        yesterday: 'Ontem',
        last7Days: 'Últimos 7 dias',
        last14Days: 'Últimos 14 dias',
        last30Days: 'Últimos 30 dias',
        last90Days: 'Últimos 90 dias',
        customize: 'Personalizar',
        allValuesConverted: 'Todos os valores convertidos para',
        noDataForPeriod: 'Nenhum dado disponível para o período selecionado',
      },
      dailyRoas: {
        title: 'Daily ROAS Control',
        subtitle: 'Gestão Diária de Campanhas e Produtos',
        market: 'Mercado',
        selectMarket: 'Selecionar Mercado',
        lowBudget: 'Low Budget',
        midBudget: 'Mid Budget',
        highBudget: 'High Budget',
        adAccount: 'Ad Account (Conta de Anúncios)',
        adAccountLabel: 'Ad Account (Conta de Anúncios):',
        selectAdAccount: 'Selecionar Ad Account',
        selectCampaignPlaceholder: 'Selecionar campanha',
        actions: 'Ações',
        updateCampaigns: 'Atualizar Campanhas',
        exportReport: 'Exportar Relatório',
        campaignsByDay: 'Campanhas por Dia',
        addCampaign: 'Adicionar Campanha',
        selectFacebookCampaign: 'Selecionar Campanha do Facebook',
        selectCampaign: 'Selecionar campanha',
        noCampaigns: 'Nenhuma campanha disponível',
        loadCampaigns: 'Carregar Campanhas',
        campaignHistory: 'Histórico da Campanha',
        noHistoryAvailable: 'Sem histórico disponível',
        noPastDays: 'Esta campanha ainda não tem dias anteriores registados.',
        day: 'Dia',
        spend: 'Gasto',
        purchases: 'Vendas',
        margin: 'Margem',
        filterByDay: 'Filtrar por Dia',
        allDays: 'Todos os Dias',
        kpis: 'KPIs',
        totalSpend: 'Gasto Total',
        totalRevenue: 'Revenue Total',
        totalSales: 'Total de Vendas',
        avgRoas: 'ROAS Médio',
        totalMarginEur: 'Margem Total (€)',
        avgMarginPerc: 'Margem Média (%)',
        chart: 'Gráfico',
        revenue_lower: 'Revenue',
        roas: 'ROAS',
        decisions: 'Decisões',
        campaign: 'Campanha',
        dateRange: 'Período',
        dayRange: 'Dias',
        atc: 'ATC',
        cpc: 'CPC',
        productPrice: 'Preço',
        cog: 'COG',
        decision: 'Decisão',
        reason: 'Motivo',
        detailsButton: 'Detalhes',
        kill: 'KILL',
        keep: 'MANTER',
        scale: 'SCALE',
        descale: 'DESCALE',
        decisionDetails: 'Detalhes da Decisão',
        integrationsNeeded: 'Integrações Necessárias',
        integrationsDesc: 'Para usar o Daily ROAS Control, precisas de ter as seguintes integrações ativas:',
        facebookAds: 'Facebook Ads',
        shopify: 'Shopify',
        integrationActive: 'Integração ativa',
        neededForCampaigns: 'Necessária para buscar campanhas e métricas',
        neededForProducts: 'Necessária para dados de produtos e vendas',
        goToSettings: 'Ir para Configurações',
        campaignUpdated: 'Campanhas atualizadas!',
        campaignsLoaded: 'campanhas carregadas.',
        noCampaignsFound: 'Nenhuma campanha encontrada',
        noActiveCampaigns: 'Esta conta não tem campanhas ativas.',
        campaignAdded: 'Campanha adicionada!',
        daysAdded: '{{count}} dia(s) adicionado(s) com sucesso.',
        campaignAlreadyExists: 'Campanha já existe',
        allDaysAlreadyExist: 'Todos os {{count}} dia(s) já estão registados.',
        errorAddingCampaign: 'Erro ao adicionar campanha',
        noDaysAdded: 'Nenhum dia foi adicionado. Verifique se há dados disponíveis.',
        reportExported: 'Relatório exportado!',
        decisionLogic: 'Lógica de Decisão Automática',
        days12: 'Dias 1-2 (Mercado {{marketType}}):',
        days3Plus: 'Dias 3+:',
        killReason1: 'Gasto ≥ limite sem vendas, ou CPC alto sem conversões',
        scaleReason1: 'Margem > 15% já nos primeiros dias',
        keepReason1: 'Há vendas ou sinais positivos (ATC, CPC baixo)',
        scaleReason2: 'Margem > 15% (aumentar orçamento)',
        keepReason2: 'Margem entre 0-15% (continuar a monitorizar)',
        killReason2: 'Margem negativa ou gasto >50€ sem vendas',
        selectCampaignDesc: 'Por favor, selecione uma campanha do Facebook primeiro.',
        productNotFound: 'Não foi possível encontrar um produto correspondente à campanha "{{campaignName}}". Os dados de COG, preço e unidades não serão preenchidos.',
        errorUpdating: 'Falha ao atualizar valores do Daily ROAS',
        selectAdAccountFirst: 'Selecione uma conta de anúncios primeiro.',
        noCampaignsRefresh: 'Nenhuma campanha encontrada. Clique em atualizar para recarregar.',
        loadingCampaigns: 'A carregar campanhas...',
        accountChanged: 'Conta de anúncios alterada',
        loadingNewAccount: 'A carregar campanhas da nova conta...',
        noDataForDay: 'Sem dados para este dia. Adiciona uma campanha acima.',
        cancel: 'Cancelar',
        add: 'Adicionar',
        waitingForMoreData: 'Aguardando mais dados para decisão ({{market}})',
        decisionDay1KillHighSpend: 'Dia 1 ({{market}}): Gasto ≥ {{spend1}}€, CPC > {{cpc}}€ e sem vendas',
        decisionDay1KeepSales: 'Dia 1 ({{market}}): {{purchases}} venda(s) - manter para dia 2',
        decisionDay1KeepLowCPC: 'Dia 1 ({{market}}): CPC < {{cpc}}€ e {{atc}} ATC - manter até {{spend2}}€',
        decisionDay1KillNoSales: 'Dia 1 ({{market}}): Gasto ≥ {{spend2}}€ sem vendas',
        decisionDay1Waiting: 'Dia 1 ({{market}}): Aguardando mais dados ({{spent}}€ gastos)',
        decisionScaleHighMargin: 'Dia {{day}} ({{market}}): Margem {{margin}}% > 15% - aumentar orçamento',
        decisionKillNegativeMargin: 'Dia {{day}} ({{market}}): Margem negativa {{margin}}%',
        decisionKeepMediumMargin: 'Dia {{day}} ({{market}}): Margem {{margin}}% (0-15%) - manter para próximo dia',
        noInsightsTitle: 'Sem dados de insights',
        noInsightsDesc: 'Esta campanha não tem dados de insights disponíveis.',
        facebookIntegrationNotFound: 'Integração Facebook não encontrada',
        connectFacebookFirst: 'Por favor, conecte sua conta do Facebook primeiro.',
        detailedAnalysis: 'Análise Detalhada da Campanha',
        allMetricsAndRecommendations: 'Todas as métricas e recomendações para esta campanha',
        allMetrics: 'Todas as Métricas',
        totalSpent: 'Total Gasto',
        units: 'Unidades',
        averageROAS: 'ROAS Médio',
        averageMargin: 'Margem Média',
        price: 'Preço €',
        actionsTable: 'Ações',
        campaignName: 'Nome Campanha',
        totalSpentEur: 'Total Gasto €',
        cpcEur: 'CPC €',
        marginEur: 'Margem €',
        marginPerc: 'Margem %',
        totalMargin: 'Margem Total',
        campaigns: 'Campanhas',
        today: 'Hoje',
        total: 'Total',
        spent: 'Gasto',
        sales: 'Vendas',
        revenue: 'Receita',
      },
      auth: {
        title: 'Sheet-Tools',
        subtitle: 'Automatize o seu ROAS e maximize lucros',
        login: 'Login',
        signUp: 'Criar Conta',
        email: 'Email',
        emailPlaceholder: 'seu@email.com',
        password: 'Palavra-passe',
        passwordPlaceholder: '••••••••',
        signIn: 'Entrar',
        signingIn: 'A entrar...',
        createAccount: 'Criar Conta',
        creatingAccount: 'A criar conta...',
        orContinueWith: 'Ou continue com',
        google: 'Google',
        backToHome: 'Voltar',
        accountCreated: 'Conta criada!',
        checkEmail: 'Verifique o seu email para confirmar o registo.',
        errorCreatingAccount: 'Erro ao criar conta',
        errorSigningIn: 'Erro ao fazer login',
        errorGoogleSignIn: 'Erro ao fazer login com Google',
        terms: 'Ao criar uma conta, concorda com os nossos Termos de Serviço e Política de Privacidade',
      },
    settings: {
      title: 'Definições',
      profile: 'Perfil',
      email: 'Email',
      emailNote: 'O email não pode ser alterado',
      fullName: 'Nome Completo',
      fullNamePlaceholder: 'João Silva',
      company: 'Nome da Empresa',
      companyPlaceholder: 'Minha Empresa Lda',
      save: 'Guardar Alterações',
      saving: 'A guardar...',
      plan: 'Plano e Faturação',
      current: 'Atual',
      upgrade: 'Fazer Upgrade',
      trialActive: 'Teste ativo',
      endsOn: 'Termina em',
      processing: 'A processar...',
      subscriptionActive: 'Subscrição Ativa',
      renewsOn: 'Renova em',
      manageSubscription: 'Gerir Subscrição',
      integrations: 'Integrações',
      facebookAds: 'Facebook Ads',
      facebookDesc: 'Importe campanhas automaticamente',
      shopify: 'Shopify',
      shopifyDesc: 'Sincronize produtos e vendas da sua loja',
      connected: 'Ligado',
      disconnect: 'Desligar',
      connect: 'Ligar',
      loading: 'A carregar definições...',
      success: 'Sucesso',
      error: 'Erro',
      profileUpdated: 'As alterações foram guardadas com sucesso.',
      integrationsPage: {
        title: 'Integrações',
        subtitle: 'Gerencie as suas conexões com plataformas externas',
        summary: 'Resumo',
        activeIntegrations: 'integração ativa',
        activeIntegrationsPlural: 'integrações ativas',
        facebookAdsTitle: 'Facebook Ads',
        facebookAdsDesc: 'Gestão de campanhas publicitárias',
        shopifyTitle: 'Shopify',
        shopifyDesc: 'Sincronização de produtos e vendas',
        addStore: 'Adicionar Loja',
        noStores: 'Nenhuma loja Shopify conectada',
        connectFirstStore: 'Conectar Primeira Loja',
        connectedOn: 'Conectado em:',
        expiresOn: 'Expira em:',
        store: 'Loja',
        sync: 'Sincronizar',
        syncing: 'Sincronizando...',
        connected: 'Conectado',
        disconnected: 'Desconectado',
        expired: 'Expirado',
        connecting: 'A conectar...',
        connectFacebook: 'Conectar Facebook Ads',
        disconnect: 'Desconectar',
        syncStarted: 'Sincronização iniciada',
        syncStartedDesc: 'Os produtos estão a ser sincronizados em background',
        syncError: 'Erro na sincronização',
        disconnectSuccess: 'Desconectado com sucesso',
        connectSuccess: 'Conectado com sucesso',
        fillAllFields: 'Por favor, preencha todos os campos',
        facebookDisconnected: 'Facebook Ads desconectado',
        facebookError: 'Não foi possível desconectar o Facebook Ads',
        shopifyDisconnected: 'Loja Shopify desconectada',
        shopifyError: 'Não foi possível desconectar a loja',
        shopifyConnectError: 'Não foi possível conectar ao Shopify',
        storesUsage: 'Lojas',
        loginRequired: 'Por favor, faça login novamente',
      },
      plans: {
        basic: {
          price: '€14.99/mês',
          annualOriginal: '179,88 €',
          annualPrice: '€134.91/ano',
          annualSavings: 'Poupe 44,97 €',
          features: ['Daily ROAS (Automático)', 'Profit Sheet', '1 loja', '15 campanhas']
        },
        standard: {
          price: '€34.99/mês',
          annualOriginal: '419,88 €',
          annualPrice: '€314.91/ano',
          annualSavings: 'Poupe 104,97 €',
          features: ['Daily ROAS (Automático)', 'Profit Sheet', 'Campanhas', 'Cotação', '2 lojas', '40 campanhas']
        },
        expert: {
          price: '€49.99/mês',
          annualOriginal: '599,88 €',
          annualPrice: '€449.91/ano',
          annualSavings: 'Poupe 149,97 €',
          features: ['Daily ROAS (Automático)', 'Profit Sheet', 'Campanhas', 'Cotação', 'Product Research', '4 lojas', 'Campanhas ilimitadas']
        },
        business: {
          price: 'Customizado',
          features: ['Tudo do Expert', 'Lojas ilimitadas', 'Suporte dedicado', 'Onboarding personalizado', 'Funcionalidades customizadas', 'Integrações sob demanda']
        }
      },
      dangerZone: {
        title: 'Zona de Perigo',
        description: 'Ações irreversíveis que afetam permanentemente a sua conta.',
        deleteAccount: 'Deletar Conta',
        deleteDescription: 'Remove permanentemente a sua conta e todos os dados associados'
      },
      shopifyDialog: {
        title: 'Ligar Shopify',
        instructions: 'Para conectar sua loja Shopify, siga estes passos:',
        step1: 'Acesse o painel de administração da sua loja Shopify',
        step2: 'Navegue para: Settings (Definições) → Apps and sales channels (Apps e canais de vendas) → Develop apps (Desenvolver apps)',
        step3: 'Clique em "Create an app" (Criar app) e atribua um nome (ex: "Dashboard Integration")',
        step4: 'Clique em "Configure Admin API scopes" (Configurar âmbitos da Admin API)',
        step5: 'Selecione as seguintes permissões obrigatórias:',
        scope1: 'read_products - Para ler informações dos produtos',
        scope2: 'read_inventory - Para ler níveis de inventário',
        scope3: 'read_orders - Para ler informações de encomendas',
        scope4: 'write_products - Para atualizar produtos (opcional)',
        step6: 'Clique em "Save" (Guardar) para salvar as permissões',
        step7: 'Clique em "Install app" (Instalar app) para gerar o token',
        step8: 'Copie o "Admin API access token" que começa com "shpat_"',
        step9: 'Cole o token no campo abaixo juntamente com o URL da sua loja',
        required: 'obrigatório',
        recommended: 'recomendado',
        optional: 'opcional',
        openAdmin: 'Abrir Shopify Admin',
        storeName: 'URL da Loja Shopify',
        storeNamePlaceholder: 'minha-loja.myshopify.com',
        storeNameHelp: 'Cole o URL da sua loja (ex: minha-loja.myshopify.com ou minha-loja.com)',
        accessToken: 'Admin API Access Token',
        accessTokenPlaceholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxx',
        accessTokenHelp: 'Token que obteve ao instalar o app (começa com shpat_)',
        cancel: 'Cancelar',
        connecting: 'A ligar...',
        connect: 'Ligar Loja',
        importantNote: 'Importante:',
        noteText: 'O token Admin API só é mostrado uma vez. Copie-o imediatamente após a instalação.',
        securityNote: 'Segurança:',
        securityText: 'Nunca partilhe este token. Ele dá acesso completo à sua loja Shopify.'
      },
      facebookWarning: {
        title: 'Requisitos para conectar Facebook Ads',
        description: 'Antes de prosseguir, certifique-se de que cumpre todos os requisitos necessários para estabelecer a conexão.',
        requirements: 'O que precisa:',
        requirement1: 'Uma conta Facebook Business Manager ativa',
        requirement2: 'Acesso ao Facebook Ads Manager com permissões de administrador',
        requirement3: 'Campanhas ativas ou historial de anúncios na sua conta',
        note: 'Se não tiver uma conta Business ou acesso ao Ads Manager, não poderá completar esta integração.',
        cancel: 'Cancelar',
        proceed: 'Continuar e Conectar'
      },
      userNotAuthenticated: 'Utilizador não autenticado',
      facebookConnectionError: 'Erro ao iniciar conexão com Facebook',
      trialExpiredTitle: 'Trial Expirado',
      trialExpiredMessage: 'O seu período de trial terminou em {{date}}. Está agora no plano FREE com funcionalidades limitadas. Faça upgrade para continuar com acesso completo.',
      fillAllFields: 'Preencha todos os campos.',
      integrationRemoved: 'Integração removida',
      shopifyDisconnected: 'Shopify desconectado e todos os produtos foram removidos.',
      facebookDisconnected: 'Facebook Ads foi desconectado.',
      errorConnecting: 'Erro ao conectar',
      checkCredentials: 'Verifique suas credenciais',
      shopifyConnected: 'Shopify conectado!',
      newStoreConnected: 'Nova loja "{{storeName}}" conectada! Os produtos da loja anterior foram removidos. Sincronize para carregar os produtos desta loja.',
      storeConnectedSuccess: 'Loja "{{storeName}}" conectada com sucesso.',
      errorSyncing: 'Erro na sincronização',
      tryAgain: 'Tente novamente',
      productsSynced: 'Produtos sincronizados!',
      syncStats: '{{created}} novos, {{updated}} atualizados de {{total}} produtos',
      errorLoadingProducts: 'Erro ao carregar produtos',
      insufficientShopifyPermissions: 'Permissões insuficientes no Shopify',
      shopifyPermissionsDesc: 'O Admin API token precisa das seguintes permissões: 1) Vá ao Shopify Admin → Settings → Apps and sales channels → Develop apps. 2) Selecione a sua app ou crie uma. 3) Em \'Admin API access scopes\', ative: read_products, read_orders, write_webhooks. 4) Instale/reinstale a app para gerar novo token. 5) Copie o novo Admin API access token. 6) Reconecte o Shopify nas Definições.',
      syncStarted: 'Sincronização iniciada!',
      syncStartedDesc: 'Os produtos estão a ser sincronizados em background. Recarregue a página em alguns segundos para ver os resultados.',
      listUpdated: 'Lista atualizada',
      productsSyncedSuccess: 'Produtos sincronizados com sucesso',
      syncFailed: 'Falha ao conectar com o Shopify. Verifique a sua ligação à internet.',
      unknownError: 'Erro desconhecido',
      invalidValue: 'Valor inválido',
      enterValidNumber: 'Por favor, insira um valor numérico válido',
      errorUpdatingQuote: 'Erro ao atualizar cotação',
      quoteUpdated: 'Cotação atualizada',
      quoteUpdatedDesc: 'Preço de fornecedor e Daily ROAS atualizados com sucesso',
      errorUpdatingQuoteDesc: 'Falha ao atualizar a cotação',
      errorLoadingData: 'Erro ao carregar dados',
    },
    billing: {
      title: 'Escolha o Seu Plano',
      subtitle: 'Gerencie suas campanhas de Facebook Ads com inteligência e simplicidade',
      monthly: 'Mensal',
      annual: 'Anual',
      perMonth: 'mês',
      perYear: 'ano',
      currentSubscription: 'Assinatura Atual',
      plan: 'Plano',
      manageBilling: 'Gerir Faturação',
      mostPopular: 'Mais Popular',
      unlimitedStores: 'lojas ilimitadas',
      stores: 'lojas',
      unlimitedCampaigns: 'campanhas ilimitadas',
      campaigns: 'campanhas',
      currentPlan: 'Plano Atual',
      choosePlan: 'Escolher Plano',
      checkoutError: 'Não foi possível iniciar o checkout. Tente novamente.',
      portalError: 'Não foi possível abrir o portal de faturação.',
    },
  },
  en: {
    common: {
      back: 'Back',
      goodbye: 'See you soon!',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      confirm: 'Confirm',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      close: 'Close',
      yes: 'Yes',
      no: 'No',
      or: 'or',
      and: 'and',
      days: 'days',
      day: 'day',
      hours: 'hours',
      minutes: 'minutes',
      seconds: 'seconds',
    },
    loadingStates: {
      title: 'Loading States',
      description: 'Examples of spinners, skeleton loaders and overlays',
      overlayTitle: 'Loading Overlay',
      showOverlay: 'Show Overlay (3 seconds)',
      processing: 'Processing data...',
    },
    trial: {
      activeMessage: 'Free Trial active - {{days}} days remaining with full Standard plan access',
      expiringWarning: 'Free Trial expires in {{days}} days! Upgrade to continue',
      upgradeNow: 'Upgrade Now',
      expired: {
        title: 'Free Trial Expired',
        description: 'Your 10-day trial period has ended. To continue using all features, choose a plan.',
        whatHappensNext: 'What happens next?',
        noAccess: 'No access to premium features',
        dataPreserved: 'Your data is preserved',
        chooseAPlan: 'Choose a plan to continue',
        maybeLater: 'Maybe Later',
        viewPlans: 'View Plans',
      },
    },
    limits: {
      exceeded: {
        stores: {
          title: 'Store Limit Reached',
          description: 'You have {{current}} stores but your plan allows only {{max}}. Remove excess stores or upgrade.',
        },
        campaigns: {
          title: 'Campaign Limit Reached',
          description: 'You have {{current}} campaigns but your plan allows only {{max}}. Remove excess campaigns or upgrade.',
        },
        howToFix: 'How to fix:',
        option1: 'Remove excess resources',
        option2: 'Upgrade to a higher plan',
        cancel: 'Cancel',
        upgradePlan: 'Upgrade Plan',
      },
    },
    subscription: {
      readOnlyTitle: 'Read-Only Mode',
      subscriptionExpired: 'Your {{planName}} subscription has expired.',
      daysUntilSuspension: 'You have {{days}} days to reactivate before suspension.',
      readOnlyCapabilities: 'In read-only mode you can:',
      viewData: 'View your data',
      exportReports: 'Export reports',
      cannotCreateCampaigns: 'Create or edit campaigns',
      cannotSyncData: 'Sync new data',
      reactivateSubscription: 'Reactivate Subscription',
      bannerExpiredTitle: '{{planName}} Subscription Expired',
      bannerExpiredDesc: 'Read-only access. {{days}} days remaining until account suspension.',
      bannerExpiredDescNoDate: 'Read-only access. Reactivate your subscription to continue.',
      reactivateNow: 'Reactivate Now',
      bannerSuspendedTitle: 'Account Suspended',
      bannerSuspendedDesc: 'Your account is suspended. In {{days}} days, your data will be permanently archived (GDPR).',
      bannerSuspendedDescNoDate: 'Your account is suspended. Reactivate to recover access.',
      recoverAccount: 'Recover Account',
      bannerArchivedTitle: 'Account Archived',
      bannerArchivedDesc: 'Your data has been anonymized. To restore access, contact support or start a new subscription.',
      newPlan: 'New Plan',
      upsellStoreTitle: 'Store Limit Reached',
      upsellStoreDesc: 'You are using {{current}}/{{limit}} stores allowed in your plan.',
      upsellCampaignTitle: 'Campaign Limit Reached',
      upsellCampaignDesc: 'You are using {{current}}/{{limit}} campaigns allowed in your plan.',
      unlockWithUpgrade: 'Unlock with upgrade:',
      unlimitedStores: 'Unlimited stores',
      automaticSync: 'Automatic synchronization',
      multiStoreManagement: 'Multi-store management',
      prioritySupport: 'Priority support',
      unlimitedCampaigns: 'Unlimited campaigns',
      advancedAutomation: 'Advanced automation',
      performanceAnalysis: 'Performance analysis',
      detailedROI: 'Detailed ROI',
      upgradeTip: 'Upgrade now and keep growing without limits',
      maybeLater: 'Maybe Later',
      viewPlans: 'View Plans',
      storeLimitReached: 'Limit Reached',
      upgradeRequired: 'Upgrade Required',
    },
    validation: {
      required: 'This field is required',
      invalidEmail: 'Invalid email address',
      emailTooLong: 'Email must be less than 255 characters',
      passwordMinLength: 'Password must be at least 8 characters',
      passwordMaxLength: 'Password must be less than 128 characters',
      nameTooShort: 'Name cannot be empty',
      nameTooLong: 'Name must be less than 100 characters',
      companyNameTooLong: 'Company name must be less than 200 characters',
      storeNameRequired: 'Store name is required',
      storeNameTooLong: 'Store name is too long',
      accessTokenRequired: 'Access token is required',
      accessTokenTooLong: 'Access token is too long',
      invalidAction: 'Invalid action',
      invalidCampaignId: 'Invalid campaign ID format',
      campaignNameTooLong: 'Campaign name must be less than 200 characters',
      budgetMustBePositive: 'Budget must be positive',
      statusMustBeValid: 'Status must be ACTIVE or PAUSED',
    },
    nav: {
      whatIsIt: 'What is it',
      features: 'Features',
      pricing: 'Pricing',
      faq: 'FAQ',
    },
    header: {
      login: 'Login',
      startFree: 'Start Free',
      getStarted: 'Get Started',
    },
    landing: {
      hero: {
        title1: 'Automate Your',
        title2: 'Facebook Campaigns',
        subtitle: 'Your smart platform for automatic metrics calculation and action recommendations.',
        benefit1: 'Calculates metrics automatically',
        benefit2: 'CPC, ROAS, CPA, Profit Margin in real-time',
        benefit3: 'Smart recommendations: Kill, Scale, Maintain',
        ctaPrimary: 'Start Free for 10 Days',
        ctaSecondary: 'What Sheet Tools does for you',
      },
      whatIsIt: {
        title: 'Smart Campaign Analysis',
        subtitle: 'Sheet Tools revolutionizes how you manage your Facebook Ads campaigns. Our platform automatically analyzes your metrics and offers precise recommendations to maximize your results.',
        smartAnalysis: {
          title: 'Smart Analysis',
          description: 'Automatically calculates CPC, ROAS, COGS, CPA, Profit Margin and other essential metrics.',
        },
        decisionAutomation: {
          title: 'Decision Automation',
          description: 'Automatic recommendations: kill bad campaigns, scale profitable ones, maintain stable ones.',
        },
      },
      features: {
        title: 'Features that make the difference',
        subtitle: 'Everything you need to optimize your campaigns in one platform',
        integration: {
          title: 'Facebook Ads Integration',
          description: 'Connect directly to your campaigns for real-time analysis',
        },
        metrics: {
          title: 'Automatic Metrics',
          description: 'ROAS, CPC, CPA, CTR, Conversion Rate calculated automatically',
        },
        ai: {
          title: 'AI for Decisions',
          description: 'Smart algorithms suggest the best actions for each campaign',
        },
        automation: {
          title: 'Complete Automation',
          description: 'Save hours of manual analysis with smart automation',
        },
        profit: {
          title: 'Profit Analysis',
          description: 'Accurate calculation of COGS, Profit Margin and real ROI',
        },
        secure: {
          title: 'Secure Data',
          description: 'Secure connection via OAuth, your data always protected',
        },
      },
      pricing: {
        title: 'Choose Your Perfect Plan',
        subtitle: 'Simple and transparent plans to automate your Facebook campaigns',
        popular: 'Most Popular',
        choosePlan: 'Choose Plan',
        monthly: 'Monthly',
        annual: 'Annual',
        save3Months: 'SAVE 3 MONTHS',
        basic: {
          name: 'Basic',
          price: '€14.99',
          perMonth: '/month',
          description: 'Profit Sheet (1 store, 15 campaigns)',
          feature1: 'Daily ROAS (Automatic in all)',
          feature2: 'Profit Sheet',
          feature3: '1 store',
          feature4: '15 campaigns',
          annualOriginal: '179.88 €',
          annualPrice: '€134.91',
          perYear: '/year',
          annualSavings: 'Save €44.97 (3 months free)',
        },
        standard: {
          name: 'Standard',
          price: '€34.99',
          perMonth: '/month',
          description: 'Profit Sheet + Campaigns + Quotation (2 stores, 40 campaigns)',
          feature1: 'Daily ROAS (Automatic in all)',
          feature2: 'Profit Sheet',
          feature3: 'Campaigns',
          feature4: 'Quotation',
          feature5: '2 stores',
          feature6: '40 campaigns',
          annualOriginal: '419.88 €',
          annualPrice: '€314.91',
          perYear: '/year',
          annualSavings: 'Save €104.97 (3 months free)',
        },
        expert: {
          name: 'Expert',
          price: '€49.99',
          perMonth: '/month',
          description: 'Standard + Product Research (4 stores, unlimited campaigns)',
          feature1: 'Daily ROAS (Automatic in all)',
          feature2: 'Profit Sheet',
          feature3: 'Campaigns',
          feature4: 'Quotation',
          feature5: 'Product Research',
          feature6: '4 stores',
          feature7: 'Unlimited campaigns',
          annualOriginal: '599.88 €',
          annualPrice: '€449.91',
          perYear: '/year',
          annualSavings: 'Save €149.97 (3 months free)',
        },
        business: {
          name: 'Business',
          price: 'Custom',
          perMonth: '',
          description: 'Fully personalized enterprise solution',
          feature1: 'Everything in Expert',
          feature2: 'Unlimited stores',
          feature3: 'Dedicated support',
          feature4: 'Personalized onboarding',
          feature5: 'Custom features',
          feature6: 'Integrations on demand',
          contactUs: 'Contact Us',
        },
        featureComparison: {
          title: 'Feature Comparison',
          feature: 'Feature',
          note: 'Note: Daily ROAS is automatic in all plans',
          dailyRoas: 'Daily ROAS (Automatic)',
          profitSheet: 'Profit Sheet',
          quotation: 'Quotation',
          campaigns: 'Campaigns',
          productResearch: 'Product Research',
          prioritySupport: 'Priority Support',
          completeHistory: 'Complete History',
        },
      },
      faq: {
        title: 'Frequently Asked Questions',
        subtitle: 'Clear your doubts about Sheet Tools',
      },
      cta: {
        title: 'Ready to automate your ROAS?',
        description: 'Join hundreds of companies that are already saving 10+ hours weekly and increased their profits by 23%',
        button: 'Start Now - 10 Days Free',
      },
    },
    faq: {
      title: 'Frequently Asked Questions',
      subtitle: 'Clear your doubts about Sheet Tools',
      q1: {
        question: 'How does automatic metrics calculation work?',
        answer: 'Sheet Tools connects directly to your Facebook Ads campaigns and automatically calculates all essential metrics like ROAS, CPC, CPA, Profit Margin, BER and much more. Data is updated in real-time.',
      },
      q2: {
        question: 'What type of recommendations does the platform offer?',
        answer: 'Based on advanced performance rules, the platform automatically suggests whether you should KILL a low-performing campaign, SCALE a profitable campaign, MAINTAIN a stable campaign or DE-SCALE when necessary.',
      },
      q3: {
        question: 'Do I need technical knowledge to use it?',
        answer: 'No! Sheet Tools was designed to be intuitive. Just connect your campaigns and the platform does all the heavy lifting of analysis and recommendations automatically.',
      },
      q4: {
        question: 'How does the free trial work?',
        answer: '10 days completely free with access to all features. No credit card required.',
      },
      q5: {
        question: 'Can I cancel at any time?',
        answer: 'Yes! There\'s no commitment. You can cancel whenever you want and continue using until the end of the paid period.',
      },
    },
    footer: {
      quickLinks: 'Quick Links',
      home: 'Home',
      features: 'Features',
      pricing: 'Pricing',
      faq: 'FAQ',
      legal: 'Legal',
      termsOfService: 'Terms of Service',
      privacyPolicy: 'Privacy Policy',
      contact: 'Contact',
      copyright: '© 2025 Sheet Tools. All rights reserved.',
    },
    stats: {
      hours: 'Hours saved per week',
      roi: 'Average ROI increase',
      companies: 'Companies trusting us',
    },
    cta: {
      title: 'Ready to automate your ROAS?',
      description: 'Join hundreds of companies that are already saving 10+ hours weekly and increased their profits by 23%',
      button: 'Start Now - 10 Days Free',
    },
    sidebar: {
      dashboard: 'Dashboard',
      campaigns: 'Campaigns',
      products: 'Products',
      settings: 'Settings',
      premium: 'Premium',
      premiumDesc: 'Unlock advanced features',
      upgrade: 'Upgrade',
      logout: 'Logout',
      dailyRoas: 'Daily ROAS',
      profitSheet: 'Profit Sheet',
      integrations: 'Integrations',
      moreOptions: 'More Options',
      support: 'Support',
      adminPanel: 'Admin Panel',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
    },
    onboarding: {
      title: 'Welcome to Sheet-Tools!',
      subtitle: 'Set up your account in 3 simple steps',
      step1Title: 'Connect Facebook Ads',
      step1Desc: 'Connect your Facebook Ads account to import campaigns',
      step2Title: 'Connect Shopify',
      step2Desc: 'Sync your products and sales from Shopify',
      step3Title: 'Add Products',
      step3Desc: 'Configure your products for ROAS analysis',
      startButton: 'Start Setup',
      skipButton: 'Skip for now',
      setupTitle: 'Setup Your Account',
      stepsCompleted: 'steps completed',
      step: 'Step',
      completed: 'Completed',
      clickToSetup: 'Click to setup',
    },
    dashboard: {
      title: 'Dashboard',
      overview: 'Overview',
      welcome: 'Welcome to Sheet-Tools! Here is an overview of your metrics.',
      of: 'of',
      avgRoas: 'Avg ROAS',
      avgCpa: 'Avg CPA',
      totalSpent: 'Total Spent',
      activeCampaigns: 'Active Campaigns',
      conversions: 'Conversions',
      activeUsers: 'Active Users',
      monthlyRevenue: 'Monthly Revenue',
      conversionRate: 'Conversion Rate',
      recentCampaigns: 'Recent Campaigns',
      nextSteps: 'Next Steps',
      connectFacebook: 'Connect Facebook Ads',
      connectFacebookDesc: 'Import your campaigns automatically',
      integrateShopify: 'Integrate Shopify',
      integrateShopifyDesc: 'Sync products and sales',
      connect: 'Connect',
      integrate: 'Integrate',
      loading: 'Loading...',
      allPeriods: 'All Periods',
      today: 'Today',
      yesterday: 'Yesterday',
      last7Days: 'Last 7 days',
      last14Days: 'Last 14 days',
      last30Days: 'Last 30 days',
      last90Days: 'Last 90 days',
      customize: 'Customize',
      totalRevenue: 'Total Revenue',
      totalProfit: 'Total Profit',
      profitMargin: 'Profit Margin',
    },
    campaigns: {
      title: 'Campaigns',
      notConnected: 'Facebook Ads not connected',
      notConnectedDesc: 'To view and manage your campaigns, you need to connect your Facebook Ads account.',
      goToSettings: 'Go to Settings',
      totalSpent: 'Total Spent',
      totalRevenue: 'Total Revenue',
      avgRoas: 'Avg ROAS',
      activeCampaigns: 'Active Campaigns',
      search: 'Search campaigns...',
      filterAll: 'All',
      filterActive: 'Active',
      filterPaused: 'Paused',
      filterArchived: 'Archived',
      refresh: 'Refresh',
      noCampaigns: 'No campaigns found.',
      spent: 'Spent',
      revenue: 'Revenue',
      roas: 'ROAS',
      cpa: 'CPA',
      conversions: 'Conversions',
      impressions: 'Impressions',
      loading: 'Loading campaigns...',
    },
    metaDashboard: {
      title: 'Ads Manager',
      loading: 'Loading Meta Dashboard...',
      connectTitle: 'Connect your Meta account',
      connectDesc: 'To access the Meta Ads Dashboard, you need to connect your Meta account first.',
      goToSettings: 'Go to Settings',
      connectedBadge: 'Connected to Meta',
      adAccount: 'Ad Account',
      selectAccount: 'Select account',
      period: 'Period',
      last7Days: 'Last 7 days',
      last30Days: 'Last 30 days',
      last90Days: 'Last 90 days',
      thisMonth: 'This month',
      today: 'Today',
      custom: 'Custom',
      refresh: 'Refresh',
      totalSpent: 'Total Spent',
      avgCPC: 'Avg CPC',
      cpm: 'CPM',
      ctr: 'CTR',
      results: 'Results',
      impressions: 'Impressions',
      spendChart: 'Spend by Campaign',
      cpcChart: 'CPC by Campaign',
      searchPlaceholder: 'Search campaigns by name...',
      filterAll: 'All',
      filterActive: 'Active',
      filterInactive: 'Inactive',
      budget: 'Budget',
      name: 'Name',
      status: 'Status',
      reach: 'Reach',
      linkClicks: 'Link Clicks',
      landingPageViews: 'Landing Page Views',
      costPerResult: 'Cost per Result',
      costPerLandingPageView: 'Cost per Landing Page View',
      roas: 'ROAS',
      spent: 'Amount Spent',
      cpc: 'CPC',
      startDate: 'Start Date',
      actions: 'Actions',
      noCampaigns: 'No campaigns found.',
      pausedSuccess: 'Campaign turned off',
      pausedDesc: 'Campaign turned off successfully.',
      activatedSuccess: 'Campaign turned on',
      activatedDesc: 'Campaign turned on successfully.',
      deletedSuccess: 'Campaign deleted',
      deletedDesc: 'Campaign deleted successfully.',
      detailsTitle: 'Campaign Details',
      detailsDesc: 'Complete information about the selected campaign',
      clicks: 'Clicks',
      spend: 'Spend',
      createdOn: 'Created on',
      dateRange: 'Date Range',
      selectRange: 'Select range',
      applyFilter: 'Apply Filter',
      confirmDeleteTitle: 'Confirm Deletion',
      confirmDeleteDesc: 'Are you sure you want to delete this campaign? This action cannot be undone.',
      confirmDelete: 'Yes, Delete',
      confirmPauseTitle: 'Confirm Turn Off',
      confirmPauseDesc: 'Are you sure you want to turn off this campaign?',
      confirmPause: 'Yes, Turn Off',
      confirmActivateTitle: 'Confirm Turn On',
      confirmActivateDesc: 'Are you sure you want to turn on this campaign?',
      confirmActivate: 'Yes, Turn On',
      cancel: 'Cancel',
      columns: 'Columns',
      viewPredefined: 'Predefined View',
      viewCustom: 'Custom View',
      selectColumns: 'Select columns to display',
      resetColumns: 'Reset to Default',
      applyColumns: 'Apply',
      connectFacebookDesc: 'Connect Facebook Ads to get started',
      errorLoadingAccounts: 'Error loading accounts',
      noAccountsFound: 'No accounts found',
      noAccountsFoundDesc: 'No ad accounts were found in your Meta account.',
      unknownErrorLoadingAccounts: 'Unknown error loading accounts',
      errorLoadingCampaigns: 'Error loading campaigns',
      unknownErrorLoadingCampaigns: 'Unknown error loading campaigns',
      error: 'Error',
      invalidCampaignId: 'Invalid campaign ID',
      errorPausing: 'Error pausing',
      unknownError: 'Unknown error',
      errorPausingCampaign: 'Error pausing campaign',
      errorActivating: 'Error activating',
      errorActivatingCampaign: 'Error activating campaign',
      errorDeleting: 'Error deleting',
      errorDeletingCampaign: 'Error deleting campaign',
      pause: 'Pause',
      activate: 'Activate',
      customize: 'Customize',
      subtitle: 'Facebook Ads Campaign Management',
      campaignsTitle: 'Campaigns',
      perDay: '/day',
      total: 'total',
      removeCampaign: 'Remove Campaign',
      active: 'Active',
      paused: 'Paused',
      editCampaign: 'Edit Campaign',
      campaignName: 'Campaign Name',
      campaignNamePlaceholder: 'Campaign name',
      dailyBudget: 'Daily Budget',
      dailyBudgetDesc: 'Leave empty if using lifetime budget',
      lifetimeBudget: 'Lifetime Budget',
      lifetimeBudgetDesc: 'Leave empty if using daily budget',
      schedule: 'Schedule',
      startTime: 'Start Date/Time',
      stopTime: 'End Date/Time',
      saveChanges: 'Save Changes',
      updatedSuccess: 'Campaign updated',
      updatedDesc: 'Campaign has been updated successfully.',
      errorUpdating: 'Error updating',
      errorUpdatingCampaign: 'Error updating campaign',
      noChanges: 'No changes',
      noChangesDesc: 'No changes were made to save.',
      viewDetails: 'View details',
      changeImage: 'Change Image',
      uploadImage: 'Upload New Image',
      currentImage: 'Current Image',
      imageUpdated: 'Image updated',
      imageUpdatedDesc: 'Campaign image has been updated successfully.',
      errorUpdatingImage: 'Error updating image',
      noImage: 'No image available',
      imageUploadDesc: 'Supported formats: JPG, PNG, GIF. Max size: 5MB',
      campaign: 'Campaign',
      adSets: 'Ad Sets',
      ads: 'Ads',
      noAdSets: 'No ad sets found',
      noAds: 'No ads found',
      adSetName: 'Ad Set Name',
      optimizationGoal: 'Optimization Goal',
      optimizationGoalPlaceholder: 'Ex: LINK_CLICKS, CONVERSIONS',
      saveAdSet: 'Save Ad Set',
      adSetUpdated: 'Ad Set updated',
      adSetUpdatedDesc: 'The ad set has been updated successfully.',
      errorUpdatingAdSet: 'Error updating ad set',
      errorLoadingAdSets: 'Error loading ad sets',
      adName: 'Ad Name',
      adTitle: 'Ad Title',
      adTitlePlaceholder: 'Ad title',
      adBody: 'Ad Body',
      adBodyPlaceholder: 'Ad body text',
      saveAd: 'Save Ad',
      adUpdated: 'Ad updated',
      adUpdatedDesc: 'The ad has been updated successfully.',
      errorUpdatingAd: 'Error updating ad',
      currency: '€',
      currencySymbol: '(€)',
      placeholderBudget: '0.00',
      billingEvent: 'Billing Event',
      billingEventPlaceholder: 'Ex: IMPRESSIONS, LINK_CLICKS',
      imageUpdated: 'Image updated',
      imageUpdatedDesc: 'Campaign image has been updated successfully.',
      errorUpdatingImage: 'Error updating image',
      noImage: 'No image available',
      imageUploadDesc: 'Supported formats: JPG, PNG, GIF. Max size: 5MB',
    },
      storeSelector: {
        selectStore: 'Select store',
        allStores: 'All Stores',
      },
      products: {
        title: 'Product Management',
        subtitle: 'Product Management and Inventory',
        totalProducts: 'Total Products',
        totalRevenue: 'Total Revenue',
        unitsSold: 'Units Sold',
        avgMargin: 'Avg Margin',
        search: 'Search products by name or SKU...',
        allStores: 'All Stores',
        allPeriods: 'All Periods',
        today: 'Today',
        total: 'Total',
        yesterday: 'Yesterday',
        last7Days: 'Last 7 days',
        last14Days: 'Last 14 days',
        last30Days: 'Last 30 days',
        last90Days: 'Last 90 days',
        customize: 'Customize',
        exportSold: 'Export Sold',
        newProduct: 'New Product',
        addProduct: 'Add New Product',
        addProductDesc: 'Fill in the product details to add to your catalog.',
        productName: 'Product Name',
        sku: 'SKU (Optional)',
        costPrice: 'Cost Price (€)',
        sellingPrice: 'Selling Price (€)',
        supplierQuote: 'Supplier Quote',
        cancel: 'Cancel',
        add: 'Add Product',
        noProducts: 'No products found',
        noProductsDesc: 'Add your first product to get started',
        adjustSearch: 'Try adjusting your search',
        sold: 'Sold',
        margin: 'Margin',
        avgPrice: 'Avg Price',
        profit: 'Profit',
        edit: 'Edit',
        loading: 'Loading products...',
        syncing: 'Syncing...',
        syncShopify: 'Sync Shopify',
        connectShopifyToStart: 'Connect your Shopify store to get started',
        noProductsSold: 'No products sold',
        syncSalesToSeeProducts: 'Sync your Shopify store sales to see sold products',
        syncingSales: 'Syncing sales...',
        syncShopifySales: 'Sync Shopify Sales',
        noProductsToExport: 'No products with sales to export',
        exportCompleted: 'Export completed',
        exportSuccess: '{{count}} products exported successfully',
        exportFileName: 'sold_products',
        exportHeaders: {
          productName: 'Product Name',
          sku: 'SKU',
          costPrice: 'Cost Price',
          sellingPrice: 'Selling Price',
          quantitySold: 'Quantity Sold',
          totalRevenue: 'Total Revenue',
          profitMargin: 'Profit Margin (%)',
          createdAt: 'Created At',
        },
      },
      productResearch: {
        title: 'Viral Product Research',
        subtitle: 'Discover viral products through Facebook Ads Library',
        underDevelopment: 'Under Development',
        comingSoon: 'This feature will be available soon',
        description: 'We are working to bring you the best viral product research experience through Facebook Ads Library.',
        feature1: '🔍 Facebook Ads Library',
        feature2: '📊 Advanced Analysis',
        feature3: '🎯 Custom Filters',
        backToDashboard: 'Back to Dashboard',
        filters: 'Search Filters',
        filtersDesc: 'Define criteria to find ads',
        customToken: 'Use Custom Token',
        recommended: 'Recommended',
        activated: 'Activated',
        deactivated: 'Deactivated',
        searchTerm: 'Search Term',
        searchPlaceholder: 'Ex: wireless earbuds, fitness tracker, skincare...',
        search: 'Search',
        searching: 'Searching...',
        period: 'Period',
        allTime: 'Last 12 months',
        last3Months: 'Last 3 months',
        lastMonth: 'Last month',
        minReach: 'Minimum Reach (impressions)',
        minDays: 'Active Days (minimum)',
        maxDays: 'Active Days (maximum)',
        countries: 'UK/EU Countries',
        selectAll: 'Select All',
        clear: 'Clear',
        adType: 'Ad Type',
        image: 'Image',
        video: 'Video',
        carousel: 'Carousel',
        link: 'Link',
        noticeTitle: 'Facebook Ads Library - UK/EU Focus',
        noticeDesc: 'This tool searches for active commercial ads delivered in the United Kingdom and European Union.',
        noticeTip: '💡 Tip: Use English search terms for better results (e.g., "wireless earbuds" instead of "auriculares sem fios")',
        statsTitle: 'Search Statistics',
        totalAds: 'Total Ads',
        avgImpressions: 'Avg Impressions',
        avgDaysActive: 'Avg Active Days',
        topCountry: 'Top Country',
        mostCommonAdType: 'Most Common Type',
        resultsTitle: 'Ads Found',
        noResults: 'No ads found with the selected criteria.',
        tryAdjust: 'Try adjusting the filters or using different search terms.',
        viewFullAd: 'View Full Ad',
        active: 'Active',
        inactive: 'Inactive',
        reach: 'Reach',
        activeFor: 'Active for',
        start: 'Start',
        selectedCountries: 'countries selected',
        selectedCountry: 'country selected',
        days: 'days',
      },
      profitSheet: {
        title: 'Profit Sheet',
        subtitle: 'Profit and Expense Analysis',
        selectStore: 'Select Store and Ad Account',
        selectStoreDesc: 'Choose Shopify store and Facebook Ads account to view Profit Sheet',
        shopifyStore: 'Shopify Store',
        adAccount: 'Ad Account',
        selectShopify: 'Select Shopify store',
        selectAdAccount: 'Select Ad Account',
        selected: 'Selected',
        confirmSelection: 'Confirm Selection',
        changeSelection: 'Change Selection',
        totalRevenue: 'Total Revenue',
        totalProfit: 'Total Profit',
        totalAdSpend: 'Total Ad Spend',
        avgRoas: 'Average ROAS',
        totalMarginEur: 'Total Margin (€)',
        avgMarginPerc: 'Average Margin (%)',
        date: 'Date',
        revenue: 'Revenue',
        cog: 'COG',
        adSpend: 'Ad Spend',
        others: 'Others',
        refunds: 'Refunds',
        fee: 'Fee',
        profit: 'Profit',
        roas: 'ROAS',
        profitMargin: 'P%',
        cogPercentage: 'COG%',
        actions: 'Actions',
        loading: 'Loading data...',
        noData: 'No data available',
        savedSuccessfully: 'Values have been updated',
        allPeriods: 'All periods',
        today: 'Today',
        total: 'Total',
        yesterday: 'Yesterday',
        last7Days: 'Last 7 days',
        last14Days: 'Last 14 days',
        last30Days: 'Last 30 days',
        last90Days: 'Last 90 days',
        customize: 'Customize',
        allValuesConverted: 'All values converted to',
        noDataForPeriod: 'No data available for the selected period',
      },
      dailyRoas: {
        title: 'Daily ROAS Control',
        subtitle: 'Daily Campaign and Product Management',
        market: 'Market',
        selectMarket: 'Select Market',
        lowBudget: 'Low Budget',
        midBudget: 'Mid Budget',
        highBudget: 'High Budget',
        adAccount: 'Ad Account',
        adAccountLabel: 'Ad Account:',
        selectAdAccount: 'Select Ad Account',
        selectCampaignPlaceholder: 'Select campaign',
        actions: 'Actions',
        updateCampaigns: 'Update Campaigns',
        exportReport: 'Export Report',
        campaignsByDay: 'Campaigns by Day',
        addCampaign: 'Add Campaign',
        selectFacebookCampaign: 'Select Facebook Campaign',
        selectCampaign: 'Select campaign',
        noCampaigns: 'No campaigns available',
        loadCampaigns: 'Load Campaigns',
        campaignHistory: 'Campaign History',
        noHistoryAvailable: 'No history available',
        noPastDays: 'This campaign has no past days recorded yet.',
        day: 'Day',
        spend: 'Spend',
        purchases: 'Purchases',
        margin: 'Margin',
        filterByDay: 'Filter by Day',
        allDays: 'All Days',
        kpis: 'KPIs',
        totalSpend: 'Total Spend',
        totalRevenue: 'Total Revenue',
        totalSales: 'Total Sales',
        avgRoas: 'Average ROAS',
        totalMarginEur: 'Total Margin (€)',
        avgMarginPerc: 'Average Margin (%)',
        chart: 'Chart',
        revenue_lower: 'Revenue',
        roas: 'ROAS',
        decisions: 'Decisions',
        campaign: 'Campaign',
        dateRange: 'Period',
        dayRange: 'Days',
        atc: 'ATC',
        cpc: 'CPC',
        productPrice: 'Price',
        cog: 'COG',
        decision: 'Decision',
        reason: 'Reason',
        detailsButton: 'Details',
        kill: 'KILL',
        keep: 'KEEP',
        scale: 'SCALE',
        descale: 'DESCALE',
        decisionDetails: 'Decision Details',
        integrationsNeeded: 'Integrations Needed',
        integrationsDesc: 'To use Daily ROAS Control, you need to have the following integrations active:',
        facebookAds: 'Facebook Ads',
        shopify: 'Shopify',
        integrationActive: 'Integration active',
        neededForCampaigns: 'Required to fetch campaigns and metrics',
        neededForProducts: 'Required for product and sales data',
        goToSettings: 'Go to Settings',
        campaignUpdated: 'Campaigns updated!',
        campaignsLoaded: 'campaigns loaded.',
        noCampaignsFound: 'No campaigns found',
        noActiveCampaigns: 'This account has no active campaigns.',
        campaignAdded: 'Campaign added!',
        daysAdded: '{{count}} day(s) added successfully.',
        campaignAlreadyExists: 'Campaign already exists',
        allDaysAlreadyExist: 'All {{count}} day(s) are already registered.',
        errorAddingCampaign: 'Error adding campaign',
        noDaysAdded: 'No days were added. Please check if data is available.',
        reportExported: 'Report exported!',
        decisionLogic: 'Automatic Decision Logic',
        days12: 'Days 1-2 (Market {{marketType}}):',
        days3Plus: 'Days 3+:',
        killReason1: 'Spend ≥ limit without sales, or high CPC without conversions',
        scaleReason1: 'Margin > 15% already in first days',
        keepReason1: 'Has sales or positive signals (ATC, low CPC)',
        scaleReason2: 'Margin > 15% (increase budget)',
        keepReason2: 'Margin between 0-15% (continue monitoring)',
        killReason2: 'Negative margin or spend >50€ without sales',
        selectCampaignDesc: 'Please select a Facebook campaign first.',
        productNotFound: 'Could not find a product matching campaign "{{campaignName}}". COG, price and units data will not be filled.',
        errorUpdating: 'Failed to update Daily ROAS values',
        selectAdAccountFirst: 'Select an ad account first.',
        noCampaignsRefresh: 'No campaigns found. Click refresh to reload.',
        loadingCampaigns: 'Loading campaigns...',
        accountChanged: 'Ad account changed',
        loadingNewAccount: 'Loading campaigns from new account...',
        noDataForDay: 'No data for this day. Add a campaign above.',
        cancel: 'Cancel',
        add: 'Add',
        waitingForMoreData: 'Waiting for more data for decision ({{market}})',
        decisionDay1KillHighSpend: 'Day 1 ({{market}}): Spent ≥ {{spend1}}€, CPC > {{cpc}}€ and no sales',
        decisionDay1KeepSales: 'Day 1 ({{market}}): {{purchases}} sale(s) - keep for day 2',
        decisionDay1KeepLowCPC: 'Day 1 ({{market}}): CPC < {{cpc}}€ and {{atc}} ATC - keep until {{spend2}}€',
        decisionDay1KillNoSales: 'Day 1 ({{market}}): Spent ≥ {{spend2}}€ without sales',
        decisionDay1Waiting: 'Day 1 ({{market}}): Waiting for more data ({{spent}}€ spent)',
        decisionScaleHighMargin: 'Day {{day}} ({{market}}): Margin {{margin}}% > 15% - increase budget',
        decisionKillNegativeMargin: 'Day {{day}} ({{market}}): Negative margin {{margin}}%',
        decisionKeepMediumMargin: 'Day {{day}} ({{market}}): Margin {{margin}}% (0-15%) - keep for next day',
        noInsightsTitle: 'No insights data',
        noInsightsDesc: 'This campaign has no insights data available.',
        facebookIntegrationNotFound: 'Facebook integration not found',
        connectFacebookFirst: 'Please connect your Facebook account first.',
        detailedAnalysis: 'Detailed Campaign Analysis',
        allMetricsAndRecommendations: 'All metrics and recommendations for this campaign',
        allMetrics: 'All Metrics',
        totalSpent: 'Total Spent',
        units: 'Units',
        averageROAS: 'Average ROAS',
        averageMargin: 'Average Margin',
        price: 'Price €',
        actionsTable: 'Actions',
        campaignName: 'Campaign Name',
        totalSpentEur: 'Total Spent €',
        cpcEur: 'CPC €',
        marginEur: 'Margin €',
        marginPerc: 'Margin %',
        totalMargin: 'Total Margin',
        campaigns: 'Campaigns',
        today: 'Today',
        total: 'Total',
        spent: 'Spent',
        sales: 'Sales',
        revenue: 'Revenue',
      },
      auth: {
        title: 'Sheet-Tools',
        subtitle: 'Automate your ROAS and maximize profits',
        login: 'Login',
        signUp: 'Sign Up',
        email: 'Email',
        emailPlaceholder: 'your@email.com',
        password: 'Password',
        passwordPlaceholder: '••••••••',
        signIn: 'Sign In',
        signingIn: 'Signing in...',
        createAccount: 'Create Account',
        creatingAccount: 'Creating account...',
        orContinueWith: 'Or continue with',
        google: 'Google',
        backToHome: 'Back',
        accountCreated: 'Account created!',
        checkEmail: 'Check your email to confirm registration.',
        errorCreatingAccount: 'Error creating account',
        errorSigningIn: 'Error signing in',
        errorGoogleSignIn: 'Error signing in with Google',
        terms: 'By creating an account, you agree to our Terms of Service and Privacy Policy',
      },
    settings: {
      title: 'Settings',
      profile: 'Profile',
      email: 'Email',
      emailNote: 'Email cannot be changed',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      company: 'Company Name',
      companyPlaceholder: 'My Company Ltd',
      save: 'Save Changes',
      saving: 'Saving...',
      plan: 'Plan & Billing',
      current: 'Current',
      upgrade: 'Upgrade',
      trialActive: 'Trial active',
      endsOn: 'Ends on',
      processing: 'Processing...',
      subscriptionActive: 'Active Subscription',
      renewsOn: 'Renews on',
      manageSubscription: 'Manage Subscription',
      integrations: 'Integrations',
      facebookAds: 'Facebook Ads',
      facebookDesc: 'Import campaigns automatically',
      shopify: 'Shopify',
      shopifyDesc: 'Sync products and sales from your store',
      connected: 'Connected',
      disconnect: 'Disconnect',
      connect: 'Connect',
      loading: 'Loading settings...',
      success: 'Success',
      error: 'Error',
      profileUpdated: 'Changes have been saved successfully.',
      integrationsPage: {
        title: 'Integrations',
        subtitle: 'Manage your connections with external platforms',
        summary: 'Summary',
        activeIntegrations: 'active integration',
        activeIntegrationsPlural: 'active integrations',
        facebookAdsTitle: 'Facebook Ads',
        facebookAdsDesc: 'Advertising campaign management',
        shopifyTitle: 'Shopify',
        shopifyDesc: 'Product and sales synchronization',
        addStore: 'Add Store',
        noStores: 'No Shopify stores connected',
        connectFirstStore: 'Connect First Store',
        connectedOn: 'Connected on:',
        expiresOn: 'Expires on:',
        store: 'Store',
        sync: 'Sync',
        syncing: 'Syncing...',
        connected: 'Connected',
        disconnected: 'Disconnected',
        expired: 'Expired',
        connecting: 'Connecting...',
        connectFacebook: 'Connect Facebook Ads',
        disconnect: 'Disconnect',
        syncStarted: 'Sync started',
        syncStartedDesc: 'Products are being synced in background',
        syncError: 'Sync error',
        disconnectSuccess: 'Successfully disconnected',
        connectSuccess: 'Successfully connected',
        fillAllFields: 'Please fill all fields',
        facebookDisconnected: 'Facebook Ads disconnected',
        facebookError: 'Unable to disconnect Facebook Ads',
        shopifyDisconnected: 'Shopify store disconnected',
        shopifyError: 'Unable to disconnect store',
        shopifyConnectError: 'Unable to connect to Shopify',
        storesUsage: 'Stores',
        loginRequired: 'Please login again',
      },
      billing: {
        monthly: 'Monthly',
        annual: 'Annual',
        save3Months: 'SAVE 3 MONTHS',
      },
      plans: {
        basic: {
          price: '€14.99/month',
          annualOriginal: '179.88 €',
          annualPrice: '€134.91/year',
          annualSavings: 'Save €44.97',
          features: ['Daily ROAS (Automatic)', 'Profit Sheet', '1 store', '15 campaigns']
        },
        standard: {
          price: '€34.99/month',
          annualOriginal: '419.88 €',
          annualPrice: '€314.91/year',
          annualSavings: 'Save €104.97',
          features: ['Daily ROAS (Automatic)', 'Profit Sheet', 'Campaigns', 'Quotation', '2 stores', '40 campaigns']
        },
        expert: {
          price: '€49.99/month',
          annualOriginal: '599.88 €',
          annualPrice: '€449.91/year',
          annualSavings: 'Save €149.97',
          features: ['Daily ROAS (Automatic)', 'Profit Sheet', 'Campaigns', 'Quotation', 'Product Research', '4 stores', 'Unlimited campaigns']
        },
        business: {
          price: 'Custom',
          features: ['Everything in Expert', 'Unlimited stores', 'Dedicated support', 'Personalized onboarding', 'Custom features', 'Integrations on demand']
        }
      },
      dangerZone: {
        title: 'Danger Zone',
        description: 'Irreversible actions that permanently affect your account.',
        deleteAccount: 'Delete Account',
        deleteDescription: 'Permanently removes your account and all associated data'
      },
      shopifyDialog: {
        title: 'Connect Shopify',
        instructions: 'To connect your Shopify store, follow these steps:',
        step1: 'Access your Shopify store admin panel',
        step2: 'Navigate to: Settings → Apps and sales channels → Develop apps',
        step3: 'Click "Create an app" and give it a name (e.g., "Dashboard Integration")',
        step4: 'Click "Configure Admin API scopes"',
        step5: 'Select the following required permissions:',
        scope1: 'read_products - To read product information',
        scope2: 'read_inventory - To read inventory levels',
        scope3: 'read_orders - To read order information',
        scope4: 'write_products - To update products (optional)',
        step6: 'Click "Save" to save permissions',
        step7: 'Click "Install app" to generate the token',
        step8: 'Copy the "Admin API access token" that starts with "shpat_"',
        step9: 'Paste the token in the field below along with your store URL',
        required: 'required',
        recommended: 'recommended',
        optional: 'optional',
        openAdmin: 'Open Shopify Admin',
        storeName: 'Shopify Store URL',
        storeNamePlaceholder: 'my-store.myshopify.com',
        storeNameHelp: 'Paste your store URL (e.g., my-store.myshopify.com or my-store.com)',
        accessToken: 'Admin API Access Token',
        accessTokenPlaceholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxx',
        accessTokenHelp: 'Token obtained when installing the app (starts with shpat_)',
        cancel: 'Cancel',
        connecting: 'Connecting...',
        connect: 'Connect Store',
        importantNote: 'Important:',
        noteText: 'The Admin API token is only shown once. Copy it immediately after installation.',
        securityNote: 'Security:',
        securityText: 'Never share this token. It provides full access to your Shopify store.'
      },
      facebookWarning: {
        title: 'Requirements to Connect Facebook Ads',
        description: 'Before proceeding, please ensure you meet all the necessary requirements to establish the connection.',
        requirements: 'What you need:',
        requirement1: 'An active Facebook Business Manager account',
        requirement2: 'Access to Facebook Ads Manager with administrator permissions',
        requirement3: 'Active campaigns or ad history in your account',
        note: 'If you don\'t have a Business account or access to Ads Manager, you won\'t be able to complete this integration.',
        cancel: 'Cancel',
        proceed: 'Continue and Connect'
      },
      userNotAuthenticated: 'User not authenticated',
      facebookConnectionError: 'Error initiating Facebook connection',
      trialExpiredTitle: 'Trial Expired',
      trialExpiredMessage: 'Your trial period ended on {{date}}. You are now on the FREE plan with limited features. Upgrade to continue with full access.',
      fillAllFields: 'Please fill all fields.',
      integrationRemoved: 'Integration removed',
      shopifyDisconnected: 'Shopify disconnected and all products were removed.',
      facebookDisconnected: 'Facebook Ads was disconnected.',
      errorConnecting: 'Error connecting',
      checkCredentials: 'Check your credentials',
      shopifyConnected: 'Shopify connected!',
      newStoreConnected: 'New store "{{storeName}}" connected! Products from the previous store were removed. Sync to load products from this store.',
      storeConnectedSuccess: 'Store "{{storeName}}" connected successfully.',
      errorSyncing: 'Sync error',
      tryAgain: 'Try again',
      productsSynced: 'Products synced!',
      syncStats: '{{created}} new, {{updated}} updated out of {{total}} products',
      errorLoadingProducts: 'Error loading products',
      insufficientShopifyPermissions: 'Insufficient Shopify permissions',
      shopifyPermissionsDesc: 'The Admin API token needs the following permissions: 1) Go to Shopify Admin → Settings → Apps and sales channels → Develop apps. 2) Select your app or create one. 3) In \'Admin API access scopes\', enable: read_products, read_orders, write_webhooks. 4) Install/reinstall the app to generate a new token. 5) Copy the new Admin API access token. 6) Reconnect Shopify in Settings.',
      syncStarted: 'Sync started!',
      syncStartedDesc: 'Products are being synced in background. Reload the page in a few seconds to see results.',
      listUpdated: 'List updated',
      productsSyncedSuccess: 'Products synced successfully',
      syncFailed: 'Failed to connect to Shopify. Check your internet connection.',
      unknownError: 'Unknown error',
      invalidValue: 'Invalid value',
      enterValidNumber: 'Please enter a valid numeric value',
      errorUpdatingQuote: 'Error updating quote',
      quoteUpdated: 'Quote updated',
      quoteUpdatedDesc: 'Supplier price and Daily ROAS updated successfully',
      errorUpdatingQuoteDesc: 'Failed to update quote',
      errorLoadingData: 'Error loading data',
    },
    billing: {
      title: 'Choose Your Plan',
      subtitle: 'Manage your Facebook Ads campaigns with intelligence and simplicity',
      monthly: 'Monthly',
      annual: 'Annual',
      perMonth: 'month',
      perYear: 'year',
      currentSubscription: 'Current Subscription',
      plan: 'Plan',
      manageBilling: 'Manage Billing',
      mostPopular: 'Most Popular',
      unlimitedStores: 'unlimited stores',
      stores: 'stores',
      unlimitedCampaigns: 'unlimited campaigns',
      campaigns: 'campaigns',
      currentPlan: 'Current Plan',
      choosePlan: 'Choose Plan',
      checkoutError: 'Could not start checkout. Please try again.',
      portalError: 'Could not open billing portal.',
    },
  },
};
