import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    const keys = key.split('.');

    const resolvePath = (lang: Language): any => {
      let val: any = translations[lang];
      for (const k of keys) {
        val = val?.[k];
      }
      return val;
    };

    let value: any = resolvePath(language);
    if (value === undefined) {
      // Fallback to English if missing in current language
      value = resolvePath('en');
    }

    let result = value ?? key;

    // Simple interpolation
    if (params && typeof result === 'string') {
      Object.keys(params).forEach(param => {
        result = result.replace(new RegExp(`{{${param}}}`, 'g'), String(params[param]));
      });
    }

    return result as string;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations = {
  pt: {
    common: {
      back: 'Voltar',
      goodbye: 'Até breve!',
      loading: 'A carregar...',
      error: 'Erro',
      success: 'Sucesso',
      cancel: 'Cancelar',
      confirm: 'Confirmar',
      save: 'Guardar',
      delete: 'Eliminar',
      edit: 'Editar',
      close: 'Fechar',
      yes: 'Sim',
      no: 'Não',
      or: 'ou',
      and: 'e',
      days: 'dias',
      day: 'dia',
      hours: 'horas',
      minutes: 'minutos',
      seconds: 'segundos',
      somethingWentWrong: 'Algo correu mal',
      unexpectedError: 'Ocorreu um erro inesperado. Por favor, tenta novamente.',
      tryAgain: 'Tentar novamente',
      goToHome: 'Ir para início',
    },
    loadingStates: {
      title: 'Loading States',
      description: 'Exemplos de spinners, skeleton loaders e overlays',
      overlayTitle: 'Loading Overlay',
      showOverlay: 'Mostrar Overlay (3 segundos)',
      processing: 'Processando dados...',
    },
    trial: {
      activeMessage: 'Free Trial ativo - {{days}} dias restantes com acesso total ao plano Standard',
      expiringWarning: 'Free Trial expira em {{days}} dias! Faça upgrade para continuar',
      upgradeNow: 'Fazer Upgrade',
      expired: {
        title: 'Free Trial Expirado',
        description: 'O seu período de teste de 10 dias terminou. Para continuar a usar todas as funcionalidades, escolha um plano.',
        whatHappensNext: 'O que acontece agora?',
        noAccess: 'Sem acesso a funcionalidades premium',
        dataPreserved: 'Os seus dados estão preservados',
        chooseAPlan: 'Escolha um plano para continuar',
        maybeLater: 'Talvez Depois',
        viewPlans: 'Ver Planos',
      },
    },
    limits: {
      exceeded: {
        stores: {
          title: 'Limite de Lojas Atingido',
          description: 'Tem {{current}} lojas mas o seu plano permite apenas {{max}}. Remova lojas em excesso ou faça upgrade.',
        },
        campaigns: {
          title: 'Limite de Campanhas Atingido',
          description: 'Tem {{current}} campanhas mas o seu plano permite apenas {{max}}. Remova campanhas em excesso ou faça upgrade.',
        },
        howToFix: 'Como resolver:',
        option1: 'Remova recursos em excesso',
        option2: 'Faça upgrade para um plano superior',
        cancel: 'Cancelar',
        upgradePlan: 'Fazer Upgrade',
      },
    },
    subscription: {
      readOnlyTitle: 'Modo de Leitura',
      subscriptionExpired: 'A sua assinatura {{planName}} expirou.',
      daysUntilSuspension: 'Tem {{days}} dias para reativar antes da suspensão.',
      readOnlyCapabilities: 'Em modo de leitura pode:',
      viewData: 'Visualizar os seus dados',
      exportReports: 'Exportar relatórios',
      cannotCreateCampaigns: 'Criar ou editar campanhas',
      cannotSyncData: 'Sincronizar novos dados',
      reactivateSubscription: 'Reativar Assinatura',
      bannerExpiredTitle: 'Assinatura {{planName}} Expirada',
      bannerExpiredDesc: 'Acesso em modo leitura. Faltam {{days}} dias até à suspensão da conta.',
      bannerExpiredDescNoDate: 'Acesso em modo leitura. Reative a sua assinatura para continuar.',
      reactivateNow: 'Reativar Agora',
      bannerSuspendedTitle: 'Conta Suspensa',
      bannerSuspendedDesc: 'A sua conta está suspensa. Em {{days}} dias, os seus dados serão arquivados permanentemente (RGPD).',
      bannerSuspendedDescNoDate: 'A sua conta está suspensa. Reative para recuperar o acesso.',
      recoverAccount: 'Recuperar Conta',
      bannerArchivedTitle: 'Conta Arquivada',
      bannerArchivedDesc: 'Os seus dados foram anonimizados. Para restaurar o acesso, contacte o suporte ou inicie uma nova assinatura.',
      newPlan: 'Novo Plano',
      upsellStoreTitle: 'Limite de Lojas Atingido',
      upsellStoreDesc: 'Está a usar {{current}}/{{limit}} lojas permitidas no seu plano.',
      upsellCampaignTitle: 'Limite de Campanhas Atingido',
      upsellCampaignDesc: 'Está a usar {{current}}/{{limit}} campanhas permitidas no seu plano.',
      unlockWithUpgrade: 'Desbloqueie com o upgrade:',
      unlimitedStores: 'Lojas ilimitadas',
      automaticSync: 'Sincronização automática',
      multiStoreManagement: 'Gestão multi-loja',
      prioritySupport: 'Suporte prioritário',
      unlimitedCampaigns: 'Campanhas ilimitadas',
      advancedAutomation: 'Automação avançada',
      performanceAnalysis: 'Análise de performance',
      detailedROI: 'ROI detalhado',
      upgradeTip: 'Faça upgrade agora e continue a crescer sem limites',
      maybeLater: 'Talvez Depois',
      viewPlans: 'Ver Planos',
      storeLimitReached: 'Limite Atingido',
      upgradeRequired: 'Upgrade Necessário',
    },
    validation: {
      required: 'Campo obrigatório',
      invalidEmail: 'Endereço de email inválido',
      emailTooLong: 'Email deve ter menos de 255 caracteres',
      passwordMinLength: 'A palavra-passe deve ter pelo menos 8 caracteres',
      passwordMaxLength: 'A palavra-passe deve ter menos de 128 caracteres',
      nameTooShort: 'O nome não pode estar vazio',
      nameTooLong: 'O nome deve ter menos de 100 caracteres',
      companyNameTooLong: 'O nome da empresa deve ter menos de 200 caracteres',
      storeNameRequired: 'O nome da loja é obrigatório',
      storeNameTooLong: 'O nome da loja é demasiado longo',
      accessTokenRequired: 'O token de acesso é obrigatório',
      accessTokenTooLong: 'O token de acesso é demasiado longo',
      invalidAction: 'Ação inválida',
      invalidCampaignId: 'ID de campanha inválido',
      campaignNameTooLong: 'O nome da campanha deve ter menos de 200 caracteres',
      budgetMustBePositive: 'O orçamento deve ser positivo',
      statusMustBeValid: 'O estado deve ser ATIVO ou PAUSADO',
    },
    nav: {
      whatIsIt: 'O que é',
      features: 'Funcionalidades',
      pricing: 'Preços',
      faq: 'FAQ',
    },
    header: {
      login: 'Entrar',
      startFree: 'Começar Grátis',
      getStarted: 'Começar',
    },
    landing: {
      hero: {
        title1: 'Automatize as suas',
        title2: 'Campanhas de Facebook',
        subtitle: 'A sua plataforma inteligente para cálculo automático de métricas e recomendações de ação.',
        benefit1: 'Calcula métricas automaticamente',
        benefit2: 'CPC, ROAS, CPA, Margem de Lucro em tempo real',
        benefit3: 'Recomendações inteligentes: Parar, Escalar, Manter',
        ctaPrimary: 'Começar Grátis por 10 Dias',
        ctaSecondary: 'O que o Sheet Tools faz por si',
      },
      whatIsIt: {
        title: 'Análise Inteligente de Campanhas',
        subtitle: 'O Sheet Tools revoluciona a forma como gere as suas campanhas de Facebook Ads. A nossa plataforma analisa automaticamente as suas métricas e oferece recomendações precisas para maximizar os seus resultados.',
        smartAnalysis: {
          title: 'Análise Inteligente',
          description: 'Calcula automaticamente CPC, ROAS, COGS, CPA, Margem de Lucro e outras métricas essenciais.',
        },
        decisionAutomation: {
          title: 'Automação de Decisões',
          description: 'Recomendações automáticas: parar campanhas ruins, escalar as rentáveis, manter as estáveis.',
        },
      },
      features: {
        title: 'Funcionalidades que fazem a diferença',
        subtitle: 'Tudo o que precisa para otimizar as suas campanhas numa só plataforma',
        integration: {
          title: 'Integração Facebook Ads',
          description: 'Ligue-se diretamente às suas campanhas para análise em tempo real',
        },
        metrics: {
          title: 'Métricas Automáticas',
          description: 'ROAS, CPC, CPA, CTR, Taxa de Conversão calculados automaticamente',
        },
        ai: {
          title: 'IA para Decisões',
          description: 'Algoritmos inteligentes sugerem as melhores ações para cada campanha',
        },
        automation: {
          title: 'Automação Completa',
          description: 'Poupe horas de análise manual com automação inteligente',
        },
        profit: {
          title: 'Análise de Lucros',
          description: 'Cálculo preciso de COGS, Margem de Lucro e ROI real',
        },
        secure: {
          title: 'Dados Seguros',
          description: 'Conexão segura via OAuth, os seus dados sempre protegidos',
        },
      },
      pricing: {
        title: 'Escolha o Seu Plano Perfeito',
        subtitle: 'Planos simples e transparentes para automatizar as suas campanhas do Facebook',
        popular: 'Mais Popular',
        choosePlan: 'Escolher Plano',
        monthly: 'Mensal',
        annual: 'Anual',
        save3Months: 'POUPE 3 MESES',
        beginner: {
          name: 'Beginner',
          price: '€4.99',
          perMonth: '/mês',
          description: 'Daily ROAS sem automação',
          feature1: 'ROAS Diário Básico',
          feature2: 'Sem automação',
          annualOriginal: '59,88 €',
          annualPrice: '€44.91',
          perYear: '/ano',
          annualSavings: 'Poupe 14,97 € (3 meses grátis)',
        },
        basic: {
          name: 'Basic',
          price: '€14.99',
          perMonth: '/mês',
          description: 'Daily ROAS + Profit Sheet (1 loja, 15 campanhas)',
          feature1: 'Daily ROAS Profit Sheet',
          feature2: '1 loja',
          feature3: '15 campanhas',
          annualOriginal: '179,88 €',
          annualPrice: '€134.91',
          perYear: '/ano',
          annualSavings: 'Poupe 44,97 € (3 meses grátis)',
        },
        standard: {
          name: 'Standard',
          price: '€34.99',
          perMonth: '/mês',
          description: 'Basic + Campanhas + Cotação (2 lojas, 40 campanhas)',
          feature1: 'Daily ROAS Profit Sheet',
          feature2: 'Campanhas',
          feature3: 'Cotação',
          feature4: '2 lojas',
          feature5: '40 campanhas',
          annualOriginal: '419,88 €',
          annualPrice: '€314.91',
          perYear: '/ano',
          annualSavings: 'Poupe 104,97 € (3 meses grátis)',
        },
        expert: {
          name: 'Expert',
          price: '€49.99',
          perMonth: '/mês',
          description: 'Standard + Product Research (4 lojas, campanhas ilimitadas)',
          feature1: 'Daily ROAS Profit Sheet',
          feature2: 'Campanhas',
          feature3: 'Cotação',
          feature4: 'Product Research',
          feature5: '4 lojas',
          annualOriginal: '599,88 €',
          annualPrice: '€449.91',
          perYear: '/ano',
          annualSavings: 'Poupe 149,97 € (3 meses grátis)',
        },
        business: {
          name: 'Business',
          price: 'Personalizado',
          description: 'Solução personalizada para grandes empresas com suporte dedicado',
          contactUs: 'Contacte-nos',
        },
        featureComparison: {
          title: 'Comparação de Funcionalidades',
          note: 'Algumas funcionalidades variam por plano. Escolha o que melhor se adapta ao seu negócio.',
          feature: 'Funcionalidade',
          dailyRoas: 'Daily ROAS',
          profitSheet: 'Profit Sheet',
          quotation: 'Cotação',
          campaigns: 'Campanhas',
          productResearch: 'Product Research',
          prioritySupport: 'Suporte Prioritário',
          completeHistory: 'Histórico Completo',
        },
      },
      faq: {
        title: 'Perguntas Frequentes',
        subtitle: 'Esclareça as suas dúvidas sobre o Sheet Tools',
      },
      cta: {
        title: 'Pronto para automatizar o seu ROAS?',
        description: 'Junte-se a centenas de empresas que já poupam 10+ horas semanais e aumentaram os seus lucros em 23%',
        button: 'Começar Agora - 10 Dias Grátis',
      },
    },
    faq: {
      title: 'Perguntas Frequentes',
      subtitle: 'Esclareça as suas dúvidas sobre o Sheet Tools',
      q1: {
        question: 'Como funciona o cálculo automático de métricas?',
        answer: 'O Sheet Tools liga-se diretamente às suas campanhas de Facebook Ads e calcula automaticamente todas as métricas essenciais como ROAS, CPC, CPA, Margem de Lucro, BER e muito mais. Os dados são atualizados em tempo real.',
      },
      q2: {
        question: 'Que tipo de recomendações a plataforma oferece?',
        answer: 'Com base em regras de performance avançadas, a plataforma sugere automaticamente se deve PARAR uma campanha de baixo desempenho, ESCALAR uma campanha rentável, MANTER uma campanha estável ou REDUZIR quando necessário.',
      },
      q3: {
        question: 'Preciso de conhecimentos técnicos para usar?',
        answer: 'Não! O Sheet Tools foi desenhado para ser intuitivo. Basta ligar as suas campanhas e a plataforma faz todo o trabalho pesado de análise e recomendações automaticamente.',
      },
      q4: {
        question: 'Como funciona o período de teste?',
        answer: '10 dias completamente grátis com acesso a todas as funcionalidades. Não é necessário cartão de crédito.',
      },
      q5: {
        question: 'Posso cancelar a qualquer momento?',
        answer: 'Sim! Não há compromisso. Pode cancelar sempre que quiser e continuar a usar até ao final do período pago.',
      },
    },
    footer: {
      quickLinks: 'Links Rápidos',
      home: 'Início',
      features: 'Funcionalidades',
      pricing: 'Preços',
      faq: 'FAQ',
      legal: 'Legal',
      termsOfService: 'Termos de Serviço',
      privacyPolicy: 'Política de Privacidade',
      contact: 'Contacto',
      copyright: '© 2025 Sheet Tools. Todos os direitos reservados.',
    },
    stats: {
      hours: 'Horas poupadas por semana',
      roi: 'Aumento médio de ROI',
      companies: 'Empresas que confiam em nós',
    },
    cta: {
      title: 'Pronto para automatizar o seu ROAS?',
      description: 'Junte-se a centenas de empresas que já poupam 10+ horas semanais e aumentaram os seus lucros em 23%',
      button: 'Começar Agora - 10 Dias Grátis',
    },
    sidebar: {
      dashboard: 'Dashboard',
      campaigns: 'Campanhas',
      products: 'Produtos',
      settings: 'Configurações',
      premium: 'Premium',
      premiumDesc: 'Desbloqueie recursos avançados',
      upgrade: 'Fazer Upgrade',
      logout: 'Sair',
      dailyRoas: 'Daily ROAS',
      profitSheet: 'Profit Sheet',
      integrations: 'Integrações',
      moreOptions: 'Mais opções',
      support: 'Suporte',
      adminPanel: 'Painel Admin',
      terms: 'Termos de Serviço',
      privacy: 'Política de Privacidade',
    },
    onboarding: {
      title: 'Bem-vindo ao Sheet-Tools!',
      subtitle: 'Configure a sua conta em 3 passos simples',
      step1Title: 'Ligar Facebook Ads',
      step1Desc: 'Ligue a sua conta do Facebook Ads para importar campanhas',
      step2Title: 'Ligar Shopify',
      step2Desc: 'Sincronize os seus produtos e vendas do Shopify',
      step3Title: 'Adicionar Produtos',
      step3Desc: 'Configure os seus produtos para análise de ROAS',
      startButton: 'Iniciar Configuração',
      skipButton: 'Saltar por agora',
      setupTitle: 'Configure a sua Conta',
      stepsCompleted: 'passos concluídos',
      step: 'Passo',
      completed: 'Concluído',
      clickToSetup: 'Clique para configurar',
    },
    dashboard: {
      title: 'Painel de Controlo',
      overview: 'Visão Geral',
      welcome: 'Bem-vindo ao Sheet-Tools! Aqui está uma visão geral das suas métricas.',
      of: 'de',
      avgRoas: 'ROAS Médio',
      avgCpa: 'CPA Médio',
      totalSpent: 'Total Gasto',
      activeCampaigns: 'Campanhas Ativas',
      activeUsers: 'Utilizadores Ativos',
      monthlyRevenue: 'Receita Mensal',
      conversionRate: 'Taxa de Conversão',
      recentCampaigns: 'Campanhas Recentes',
      nextSteps: 'Próximos Passos',
      connectFacebook: 'Ligar Facebook Ads',
      connectFacebookDesc: 'Importe as suas campanhas automaticamente',
      integrateShopify: 'Integrar Shopify',
      integrateShopifyDesc: 'Sincronize produtos e vendas',
      connect: 'Ligar',
      integrate: 'Integrar',
      loading: 'A carregar...',
      totalRevenue: 'Receita Total',
      totalAdSpend: 'Gasto Total em Anúncios',
      profit: 'Lucro',
      averageRoas: 'ROAS Médio',
      totalSupplierCost: 'Gasto Total em Fornecedor',
      conversions: 'Conversões',
      averageCpc: 'CPC Médio',
      profitMargin: 'Margem de Lucro',
      recentlyUsed: 'Utilizados recentemente',
      filters: 'Filtros',
      refresh: 'Atualizar',
      dailyRevenue: 'Receita Diária',
      dailyProfit: 'Lucro Diário',
      dailySpend: 'Gasto Diário',
      campaign: 'Campanha',
      platform: 'Plataforma',
      spent: 'Gasto',
      revenue: 'Receita',
      status: 'Status',
      searchCampaigns: 'Buscar campanhas...',
      noActiveCampaigns: 'Nenhuma campanha ativa encontrada.',
      noCampaignsMatch: 'Nenhuma campanha corresponde à busca.',
      showMore: 'Ver Mais',
      showLess: 'Ver Menos',
      noName: 'Sem nome',
      campaigns: 'campanhas',
      timeframe: 'Período',
      refreshed: 'Atualizado',
      dataRefreshed: 'Dados atualizados com sucesso',
      clickToAddQuotes: 'Clique para adicionar cotações',
      selectFilters: 'Selecione Filtros para Ver Campanhas',
      selectFiltersDescription: 'Para otimizar o carregamento, selecione uma loja ou conta de anúncios nos filtros acima para visualizar as campanhas.',
    },
    campaigns: {
      title: 'Campanhas',
      notConnected: 'Facebook Ads não ligado',
      notConnectedDesc: 'Para visualizar e gerir as suas campanhas, precisa de ligar a sua conta do Facebook Ads.',
      goToSettings: 'Ir para Definições',
      totalSpent: 'Total Gasto',
      totalRevenue: 'Receita Total',
      avgRoas: 'ROAS Médio',
      activeCampaigns: 'Campanhas Ativas',
      search: 'Pesquisar campanhas...',
      filterAll: 'Todas',
      filterActive: 'Ativa',
      filterPaused: 'Pausada',
      filterArchived: 'Arquivada',
      refresh: 'Atualizar',
      noCampaigns: 'Nenhuma campanha encontrada.',
      spent: 'Gasto',
      revenue: 'Receita',
      roas: 'ROAS',
      cpa: 'CPA',
      conversions: 'Conversões',
      impressions: 'Impressões',
      loading: 'A carregar campanhas...',
    },
    metaDashboard: {
      title: 'Ads Manager',
      loading: 'A carregar Meta Dashboard...',
      connectTitle: 'Conecte a sua conta Meta',
      connectDesc: 'Para aceder ao Meta Ads Dashboard, precisa de conectar a sua conta Meta primeiro.',
      goToSettings: 'Ir para Definições',
      connectedBadge: 'Ligado à Meta',
      adAccount: 'Conta de Anúncios',
      selectAccount: 'Selecionar conta',
      period: 'Período',
      last7Days: 'Últimos 7 dias',
      last30Days: 'Últimos 30 dias',
      last90Days: 'Últimos 90 dias',
      thisMonth: 'Este mês',
      today: 'Hoje',
      custom: 'Personalizado',
      refresh: 'Atualizar',
      totalSpent: 'Montante Gasto',
      avgCPC: 'CPC Médio',
      activeCampaigns: 'Campanhas Ativas',
      serverError: 'Erro no servidor. Por favor, tente novamente mais tarde ou verifique sua conexão com o Facebook.',
      cpm: 'CPM',
      ctr: 'CTR',
      results: 'Resultados',
      impressions: 'Impressões',
      spendChart: 'Gasto por Campanha',
      cpcChart: 'CPC por Campanha',
      searchPlaceholder: 'Pesquisar campanhas por nome...',
      filterAll: 'Todos',
      filterActive: 'Ativas',
      filterInactive: 'Inativas',
      name: 'Nome',
      status: 'Estado',
      budget: 'Orçamento',
      reach: 'Alcance',
      linkClicks: 'Cliques na Ligação',
      landingPageViews: 'Visualização na Página',
      costPerResult: 'Custo por Resultado',
      costPerLandingPageView: 'Custo por visualização da página',
      roas: 'ROAS',
      spent: 'Montante Gasto',
      cpc: 'CPC',
      startDate: 'Data Início',
      actions: 'Ações',
      noCampaigns: 'Nenhuma campanha encontrada.',
      pausedSuccess: 'Campanha desligada',
      pausedDesc: 'A campanha foi desligada com sucesso.',
      activatedSuccess: 'Campanha ligada',
      activatedDesc: 'A campanha foi ligada com sucesso.',
      deletedSuccess: 'Campanha eliminada',
      deletedDesc: 'A campanha foi eliminada com sucesso.',
      detailsTitle: 'Detalhes da Campanha',
      detailsDesc: 'Informação completa sobre a campanha selecionada',
      clicks: 'Cliques',
      spend: 'Gasto',
      createdOn: 'Criado em',
      dateRange: 'Intervalo de Datas',
      selectRange: 'Selecionar intervalo',
      applyFilter: 'Aplicar Filtro',
      confirmDeleteTitle: 'Confirmar Eliminação',
      confirmDeleteDesc: 'Tem a certeza de que deseja eliminar esta campanha? Esta ação não pode ser revertida.',
      confirmDelete: 'Sim, Eliminar',
      confirmPauseTitle: 'Confirmar Desligar',
      confirmPauseDesc: 'Tem a certeza de que deseja desligar esta campanha?',
      confirmPause: 'Sim, Desligar',
      confirmActivateTitle: 'Confirmar Ligar',
      confirmActivateDesc: 'Tem a certeza de que deseja ligar esta campanha?',
      confirmActivate: 'Sim, Ligar',
      cancel: 'Cancelar',
      columns: 'Colunas',
      viewPredefined: 'Vista Pré-definida',
      viewCustom: 'Vista Personalizada',
      selectColumns: 'Selecionar colunas a mostrar',
      resetColumns: 'Repor Pré-definição',
      applyColumns: 'Aplicar',
      connectFacebookDesc: 'Conecte o Facebook Ads para começar',
      errorLoadingAccounts: 'Erro ao carregar contas',
      noAccountsFound: 'Nenhuma conta encontrada',
      noAccountsFoundDesc: 'Não foram encontradas contas de anúncios na sua conta Meta.',
      unknownErrorLoadingAccounts: 'Erro desconhecido ao carregar contas',
      errorLoadingCampaigns: 'Erro ao carregar campanhas',
      unknownErrorLoadingCampaigns: 'Erro desconhecido ao carregar campanhas',
      error: 'Erro',
      invalidCampaignId: 'ID da campanha inválido',
      errorPausing: 'Erro ao pausar',
      unknownError: 'Erro desconhecido',
      errorPausingCampaign: 'Erro ao pausar campanha',
      errorActivating: 'Erro ao ativar',
      errorActivatingCampaign: 'Erro ao ativar campanha',
      errorDeleting: 'Erro ao eliminar',
      errorDeletingCampaign: 'Erro ao eliminar campanha',
      pause: 'Pausar',
      activate: 'Ativar',
      customize: 'Personalizar',
      subtitle: 'Gestão de Campanhas do Facebook Ads',
      campaignsTitle: 'Campanhas',
      perDay: '/dia',
      total: 'total',
      removeCampaign: 'Remover Campanha',
      active: 'Active',
      paused: 'Paused',
      editCampaign: 'Editar Campanha',
      campaignName: 'Nome da Campanha',
      campaignNamePlaceholder: 'Nome da campanha',
      dailyBudget: 'Orçamento Diário',
      dailyBudgetDesc: 'Deixe vazio se usar orçamento total',
      lifetimeBudget: 'Orçamento Total',
      lifetimeBudgetDesc: 'Deixe vazio se usar orçamento diário',
      schedule: 'Horários',
      startTime: 'Data/Hora de Início',
      stopTime: 'Data/Hora de Fim',
      saveChanges: 'Salvar Alterações',
      updatedSuccess: 'Campanha atualizada',
      updatedDesc: 'A campanha foi atualizada com sucesso.',
      errorUpdating: 'Erro ao atualizar',
      errorUpdatingCampaign: 'Erro ao atualizar campanha',
      noChanges: 'Sem alterações',
      noChangesDesc: 'Não foram feitas alterações para salvar.',
      viewDetails: 'Ver detalhes',
      changeImage: 'Alterar Imagem',
      uploadImage: 'Carregar Nova Imagem',
      currentImage: 'Imagem Atual',
      imageUpdated: 'Imagem atualizada',
      imageUpdatedDesc: 'A imagem da campanha foi atualizada com sucesso.',
      errorUpdatingImage: 'Erro ao atualizar imagem',
      noImage: 'Nenhuma imagem disponível',
      imageUploadDesc: 'Formatos suportados: JPG, PNG, GIF. Tamanho máximo: 5MB',
      campaign: 'Campanha',
      adSets: 'Ad Sets',
      ads: 'Anúncios',
      noAdSets: 'Nenhum ad set encontrado',
      noAds: 'Nenhum anúncio encontrado',
      adSetName: 'Nome do Ad Set',
      optimizationGoal: 'Objetivo de Otimização',
      optimizationGoalPlaceholder: 'Ex: LINK_CLICKS, CONVERSIONS',
      saveAdSet: 'Salvar Ad Set',
      adSetUpdated: 'Ad Set atualizado',
      adSetUpdatedDesc: 'O ad set foi atualizado com sucesso.',
      errorUpdatingAdSet: 'Erro ao atualizar ad set',
      errorLoadingAdSets: 'Erro ao carregar ad sets',
      adName: 'Nome do Anúncio',
      adTitle: 'Título do Anúncio',
      adTitlePlaceholder: 'Título do anúncio',
      adBody: 'Texto do Anúncio',
      adBodyPlaceholder: 'Texto do anúncio',
      saveAd: 'Salvar Anúncio',
      adUpdated: 'Anúncio atualizado',
      adUpdatedDesc: 'O anúncio foi atualizado com sucesso.',
      errorUpdatingAd: 'Erro ao atualizar anúncio',
      currency: '€',
      currencySymbol: '(€)',
      placeholderBudget: '0.00',
      billingEvent: 'Evento de Faturamento',
      billingEventPlaceholder: 'Ex: IMPRESSIONS, LINK_CLICKS',
      activeDays: 'Dias Ativos',
    },
      storeSelector: {
        selectStore: 'Selecionar loja',
        allStores: 'Todas as Lojas',
      },
      products: {
        title: 'Gestão de Produtos',
        subtitle: 'Gestão de Produtos e Inventário',
        totalProducts: 'Total de Produtos',
        totalRevenue: 'Receita Total',
        totalProfit: 'Lucro Total',
        unitsSold: 'Unidades Vendidas',
        avgMargin: 'Margem Média',
        noCostPrice: 'Sem Custo',
        needsQuote: 'Adicionar cotação para calcular',
        incompleteCosts: 'Custos incompletos',
        clickToAddQuotes: 'Clique para adicionar cotações',
        withoutCost: 'Sem cotação',
        search: 'Pesquisar produtos por nome ou SKU...',
        allStores: 'Todas as Lojas',
        allPeriods: 'Todos os períodos',
        today: 'Hoje',
        total: 'Total',
        yesterday: 'Ontem',
        last7Days: 'Últimos 7 dias',
        last14Days: 'Últimos 14 dias',
        last30Days: 'Últimos 30 dias',
        last90Days: 'Últimos 90 dias',
        customize: 'Personalizar',
        exportSold: 'Exportar Vendidos',
        newProduct: 'Novo Produto',
        addProduct: 'Adicionar Novo Produto',
        addProductDesc: 'Preencha os detalhes do produto para adicionar ao seu catálogo.',
        productName: 'Nome do Produto',
        sku: 'SKU (Opcional)',
        costPrice: 'Preço de Custo (€)',
        sellingPrice: 'Preço de Venda (€)',
        supplierQuote: 'Cotação (Fornecedor)',
        cancel: 'Cancelar',
        add: 'Adicionar Produto',
        noProducts: 'Nenhum produto encontrado',
        noProductsDesc: 'Adicione o seu primeiro produto para começar',
        adjustSearch: 'Tente ajustar a pesquisa',
        sold: 'Vendidos',
        margin: 'Margem',
        avgPrice: 'Preço Médio',
        profit: 'Profit',
        edit: 'Editar',
        viewInShopify: 'Ver na Shopify',
        loading: 'A carregar produtos...',
        syncing: 'A sincronizar...',
        syncShopify: 'Sincronizar Shopify',
        connectShopifyToStart: 'Conecte sua loja Shopify para começar',
        noProductsSold: 'Nenhum produto vendido',
        syncSalesToSeeProducts: 'Sincronize as vendas da sua loja Shopify para ver os produtos vendidos',
        syncingSales: 'A sincronizar vendas...',
        syncShopifySales: 'Sincronizar Vendas Shopify',
        noProductsToExport: 'Não há produtos com vendas para exportar',
        exportCompleted: 'Exportação concluída',
        exportSuccess: '{{count}} produtos exportados com sucesso',
        exportFileName: 'produtos_vendidos',
        exportHeaders: {
          productName: 'Nome do Produto',
          sku: 'SKU',
          costPrice: 'Preço de Fornecedor',
          sellingPrice: 'Preço de Venda',
          quantitySold: 'Unidades Vendidas',
          totalRevenue: 'Receita Total',
          profitMargin: 'Margem de Lucro (%)',
          createdAt: 'Data de Criação',
        },
      },
      productResearch: {
        title: 'Pesquisa de Produtos Virais',
        subtitle: 'Descobre produtos virais através da Facebook Ads Library',
        underDevelopment: 'Em Desenvolvimento',
        comingSoon: 'Esta funcionalidade estará disponível em breve',
        description: 'Estamos a trabalhar para trazer-te a melhor experiência de pesquisa de produtos virais através da Facebook Ads Library.',
        feature1: '🔍 Facebook Ads Library',
        feature2: '📊 Análise Avançada',
        feature3: '🎯 Filtros Personalizados',
        backToDashboard: 'Voltar ao Dashboard',
        searchFilters: 'Filtros de Pesquisa',
        searchDescription: 'Pesquisa anúncios do Facebook para encontrar produtos virais',
        keyword: 'Palavra-chave',
        keywordPlaceholder: 'Ex: dropshipping, ecommerce...',
        country: 'País',
        dateRange: 'Período',
        sortBy: 'Ordenar por',
        last7Days: 'Últimos 7 dias',
        last30Days: 'Últimos 30 dias',
        last90Days: 'Últimos 90 dias',
        lastYear: 'Último ano',
        minImpressions: 'Impressões Mínimas',
        mostRecent: 'Mais Recentes',
        oldestFirst: 'Mais Antigos',
        mostImpressions: 'Mais Impressões',
        leastImpressions: 'Menos Impressões',
        highestSpend: 'Maior Gasto',
        lowestSpend: 'Menor Gasto',
        longestRunning: 'Mais Tempo Ativo',
        shortestRunning: 'Menos Tempo Ativo',
        search: 'Pesquisar',
        export: 'Exportar CSV',
        selectAll: 'Selecionar Todos',
        resultsCount: '{{count}} resultados encontrados',
        viewAd: 'Ver Anúncio',
        noResults: 'Use os filtros acima para pesquisar anúncios',
        enterSearchTerm: 'Introduza um termo de pesquisa',
        foundAds: '{{count}} anúncios encontrados',
        noAdsFound: 'Nenhum anúncio encontrado',
        searchError: 'Erro ao pesquisar anúncios',
        loginRequired: 'É necessário fazer login',
        adSaved: 'Anúncio guardado com sucesso',
        adRemoved: 'Anúncio removido dos guardados',
        saveError: 'Erro ao guardar anúncio',
        selectAdsToExport: 'Selecione anúncios para exportar',
        exportSuccess: 'Exportação concluída com sucesso',
      },
      facebook: {
        connectAccount: 'Conectar Conta Facebook',
        connectDesc: 'Para pesquisar anúncios, conecta a tua conta do Facebook',
        connectButton: 'Conectar com Facebook',
        reconnect: 'Reconectar Facebook',
        tokenExpired: 'O teu token do Facebook expirou. Por favor reconecta.',
        reconnectButton: 'Reconectar Agora',
        connectedAs: 'Conectado como',
        expiresOn: 'Expira em',
        disconnect: 'Desconectar',
        disconnected: 'Facebook desconectado',
        disconnectedDesc: 'A tua conta do Facebook foi desconectada.',
        error: 'Erro',
        disconnectError: 'Erro ao desconectar Facebook',
      },
      metaConnect: {
        last3Months: 'Últimos 3 meses',
        lastMonth: 'Último mês',
        minReach: 'Alcance Mínimo (impressões)',
        minDays: 'Dias Ativos (mínimo)',
        maxDays: 'Dias Ativos (máximo)',
        countries: 'Países UK/UE',
        selectAll: 'Selecionar Todos',
        clear: 'Limpar',
        adType: 'Tipo de Anúncio',
        image: 'Imagem',
        video: 'Vídeo',
        carousel: 'Carrossel',
        link: 'Link',
        noticeTitle: 'Facebook Ads Library - Foco UK/UE',
        noticeDesc: 'Esta ferramenta pesquisa anúncios comerciais ativos entregues no Reino Unido e União Europeia.',
        noticeTip: '💡 Dica: Usa termos de pesquisa em inglês para melhores resultados (ex: "wireless earbuds" em vez de "auriculares sem fios")',
        statsTitle: 'Estatísticas da Pesquisa',
        totalAds: 'Total de Anúncios',
        avgImpressions: 'Média de Impressões',
        avgDaysActive: 'Média de Dias Ativos',
        topCountry: 'País Principal',
        mostCommonAdType: 'Tipo Mais Comum',
        resultsTitle: 'Anúncios Encontrados',
        noResults: 'Nenhum anúncio encontrado com os critérios selecionados.',
        tryAdjust: 'Tenta ajustar os filtros ou usar termos de pesquisa diferentes.',
        viewFullAd: 'Ver Anúncio Completo',
        active: 'Ativo',
        inactive: 'Inativo',
        reach: 'Alcance',
        activeFor: 'Ativo há',
        start: 'Início',
        selectedCountries: 'países selecionados',
        selectedCountry: 'país selecionado',
        days: 'dias',
      },
      supplierQuotes: {
        title: 'Cotações de Fornecedores',
        description: 'Gerencie pedidos de cotação para fornecedores',
        requestQuote: 'Solicitar Cotação',
        createSession: 'Criar Sessão de Cotação',
        createSessionDescription: 'Crie um link único para o fornecedor enviar cotações',
        supplierName: 'Nome do Fornecedor',
        supplierEmail: 'Email do Fornecedor (Opcional)',
        selectProducts: 'Selecionar Produtos',
        selectAll: 'Selecionar Todos',
        clearSelection: 'Limpar',
        noProducts: 'Nenhum produto disponível para esta loja',
        generateLink: 'Gerar Link',
        generatedLink: 'Link Gerado',
        shareLinkWithSupplier: 'Partilhe este link com o seu fornecedor',
        noSessions: 'Nenhuma sessão de cotação criada ainda',
        openLink: 'Abrir Link',
        deleteSessionConfirm: 'Tem certeza que deseja eliminar esta sessão de cotação? Esta ação não pode ser desfeita.',
      },
      profitSheet: {
        title: 'Profit Sheet',
        subtitle: 'Análise de Lucros e Gastos',
        selectStore: 'Selecionar Loja e Conta de Anúncios',
        selectStoreDesc: 'Escolhe a loja Shopify e a conta de Facebook Ads para visualizar o Profit Sheet',
        shopifyStore: 'Loja Shopify',
        adAccount: 'Ad Account (Conta de Anúncios)',
        selectShopify: 'Selecionar loja Shopify',
        selectAdAccount: 'Selecionar Ad Account',
        selected: 'Selecionada',
        confirmSelection: 'Confirmar Seleção',
        changeSelection: 'Alterar Seleção',
        totalRevenue: 'Revenue Total',
        totalProfit: 'Profit Total',
        totalAdSpend: 'Ad Spend Total',
        avgRoas: 'ROAS Médio',
        totalMarginEur: 'Margem Total (€)',
        avgMarginPerc: 'Margem Média (%)',
        date: 'Data',
        revenue: 'Revenue',
        cog: 'COG',
        adSpend: 'Ad Spend',
        others: 'Outros',
        refunds: 'Refunds',
        fee: 'Taxa',
        profit: 'Profit',
        roas: 'ROAS',
        profitMargin: 'P%',
        cogPercentage: 'COG%',
        actions: 'Ações',
        loading: 'A carregar dados...',
        noData: 'Nenhum dado disponível',
        savedSuccessfully: 'Os valores foram atualizados',
        allPeriods: 'Todos os períodos',
        today: 'Hoje',
        total: 'Total',
        yesterday: 'Ontem',
        last7Days: 'Últimos 7 dias',
        last14Days: 'Últimos 14 dias',
        last30Days: 'Últimos 30 dias',
        last90Days: 'Últimos 90 dias',
        customize: 'Personalizar',
        allValuesConverted: 'Todos os valores convertidos para',
        noDataForPeriod: 'Nenhum dado disponível para o período selecionado',
      },
      dailyRoas: {
        title: 'Daily ROAS Control',
        subtitle: 'Gestão Diária de Campanhas e Produtos',
        market: 'Mercado',
        selectMarket: 'Selecionar Mercado',
        lowBudget: 'Low Budget',
        midBudget: 'Mid Budget',
        highBudget: 'High Budget',
        adAccount: 'Ad Account (Conta de Anúncios)',
        adAccountLabel: 'Ad Account (Conta de Anúncios):',
        selectAdAccount: 'Selecionar Ad Account',
        selectCampaignPlaceholder: 'Selecionar campanha',
        actions: 'Ações',
        updateCampaigns: 'Atualizar Campanhas',
        exportReport: 'Exportar Relatório',
        campaignsByDay: 'Campanhas por Dia',
        addCampaign: 'Adicionar Campanha',
        selectFacebookCampaign: 'Selecionar Campanha do Facebook',
        selectCampaign: 'Selecionar campanha',
        noCampaigns: 'Nenhuma campanha disponível',
        loadCampaigns: 'Carregar Campanhas',
        campaignHistory: 'Histórico da Campanha',
        noHistoryAvailable: 'Sem histórico disponível',
        noPastDays: 'Esta campanha ainda não tem dias anteriores registados.',
        day: 'Dia',
        spend: 'Gasto',
        purchases: 'Vendas',
        margin: 'Margem',
        filterByDay: 'Filtrar por Dia',
        allDays: 'Todos os Dias',
        kpis: 'KPIs',
        totalSpend: 'Gasto Total',
        totalRevenue: 'Revenue Total',
        totalSales: 'Total de Vendas',
        avgRoas: 'ROAS Médio',
        totalMarginEur: 'Margem Total (€)',
        avgMarginPerc: 'Margem Média (%)',
        chart: 'Gráfico',
        revenue_lower: 'Revenue',
        roas: 'ROAS',
        decisions: 'Decisões',
        campaign: 'Campanha',
        dateRange: 'Período',
        dayRange: 'Dias',
        atc: 'ATC',
        cpc: 'CPC',
        productPrice: 'Preço',
        cog: 'COG',
        decision: 'Decisão',
        reason: 'Motivo',
        detailsButton: 'Detalhes',
        kill: 'KILL',
        keep: 'MANTER',
        scale: 'SCALE',
        descale: 'DESCALE',
        decisionDetails: 'Detalhes da Decisão',
        integrationsNeeded: 'Integrações Necessárias',
        integrationsDesc: 'Para usar o Daily ROAS Control, precisas de ter as seguintes integrações ativas:',
        facebookAds: 'Facebook Ads',
        shopify: 'Shopify',
        integrationActive: 'Integração ativa',
        neededForCampaigns: 'Necessária para buscar campanhas e métricas',
        neededForProducts: 'Necessária para dados de produtos e vendas',
        goToSettings: 'Ir para Configurações',
        campaignUpdated: 'Campanhas atualizadas!',
        campaignsLoaded: 'campanhas carregadas.',
        noCampaignsFound: 'Nenhuma campanha encontrada',
        noActiveCampaigns: 'Esta conta não tem campanhas ativas.',
        campaignAdded: 'Campanha adicionada!',
        daysAdded: '{{count}} dia(s) adicionado(s) com sucesso.',
        campaignAlreadyExists: 'Campanha já existe',
        allDaysAlreadyExist: 'Todos os {{count}} dia(s) já estão registados.',
        errorAddingCampaign: 'Erro ao adicionar campanha',
        noDaysAdded: 'Nenhum dia foi adicionado. Verifique se há dados disponíveis.',
        reportExported: 'Relatório exportado!',
        decisionLogic: 'Lógica de Decisão Automática',
        days12: 'Dias 1-2 (Mercado {{marketType}}):',
        days3Plus: 'Dias 3+:',
        killReason1: 'Gasto ≥ limite sem vendas, ou CPC alto sem conversões',
        scaleReason1: 'Margem > 15% já nos primeiros dias',
        keepReason1: 'Há vendas ou sinais positivos (ATC, CPC baixo)',
        scaleReason2: 'Margem > 15% (aumentar orçamento)',
        keepReason2: 'Margem entre 0-15% (continuar a monitorizar)',
        killReason2: 'Margem negativa ou gasto >50€ sem vendas',
        selectCampaignDesc: 'Por favor, selecione uma campanha do Facebook primeiro.',
        productNotFound: 'Não foi possível encontrar um produto correspondente à campanha "{{campaignName}}". Os dados de COG, preço e unidades não serão preenchidos.',
        errorUpdating: 'Falha ao atualizar valores do Daily ROAS',
        selectAdAccountFirst: 'Selecione uma conta de anúncios primeiro.',
        noCampaignsRefresh: 'Nenhuma campanha encontrada. Clique em atualizar para recarregar.',
        loadingCampaigns: 'A carregar campanhas...',
        accountChanged: 'Conta de anúncios alterada',
        loadingNewAccount: 'A carregar campanhas da nova conta...',
        noDataForDay: 'Sem dados para este dia. Adiciona uma campanha acima.',
        cancel: 'Cancelar',
        add: 'Adicionar',
        waitingForMoreData: 'Aguardando mais dados para decisão ({{market}})',
        decisionDay1KillHighSpend: 'Dia 1 ({{market}}): Gasto ≥ {{spend1}}€, CPC > {{cpc}}€ e sem vendas',
        decisionDay1KeepSales: 'Dia 1 ({{market}}): {{purchases}} venda(s) - manter para dia 2',
        decisionDay1KeepLowCPC: 'Dia 1 ({{market}}): CPC < {{cpc}}€ e {{atc}} ATC - manter até {{spend2}}€',
        decisionDay1KillNoSales: 'Dia 1 ({{market}}): Gasto ≥ {{spend2}}€ sem vendas',
        decisionDay1Waiting: 'Dia 1 ({{market}}): Aguardando mais dados ({{spent}}€ gastos)',
        decisionScaleHighMargin: 'Dia {{day}} ({{market}}): Margem {{margin}}% > 15% - aumentar orçamento',
        decisionKillNegativeMargin: 'Dia {{day}} ({{market}}): Margem negativa {{margin}}%',
        decisionKeepMediumMargin: 'Dia {{day}} ({{market}}): Margem {{margin}}% (0-15%) - manter para próximo dia',
        noInsightsTitle: 'Sem dados de insights',
        noInsightsDesc: 'Esta campanha não tem dados de insights disponíveis.',
        facebookIntegrationNotFound: 'Integração Facebook não encontrada',
        connectFacebookFirst: 'Por favor, conecte sua conta do Facebook primeiro.',
        detailedAnalysis: 'Análise Detalhada da Campanha',
        allMetricsAndRecommendations: 'Todas as métricas e recomendações para esta campanha',
        allMetrics: 'Todas as Métricas',
        totalSpent: 'Total Gasto',
        units: 'Unidades',
        averageROAS: 'ROAS Médio',
        averageMargin: 'Margem Média',
        price: 'Preço €',
        actionsTable: 'Ações',
        campaignName: 'Nome Campanha',
        totalSpentEur: 'Total Gasto €',
        cpcEur: 'CPC €',
        marginEur: 'Margem €',
        marginPerc: 'Margem %',
        totalMargin: 'Margem Total',
        campaigns: 'Campanhas',
        today: 'Hoje',
        total: 'Total',
        spent: 'Gasto',
        sales: 'Vendas',
        revenue: 'Receita',
      },
      auth: {
        title: 'Sheet-Tools',
        subtitle: 'Automatize o seu ROAS e maximize lucros',
        login: 'Login',
        signUp: 'Criar Conta',
        email: 'Email',
        emailPlaceholder: 'seu@email.com',
        password: 'Palavra-passe',
        passwordPlaceholder: '••••••••',
        signIn: 'Entrar',
        signingIn: 'A entrar...',
        createAccount: 'Criar Conta',
        creatingAccount: 'A criar conta...',
        orContinueWith: 'Ou continue com',
        google: 'Google',
        backToHome: 'Voltar',
        accountCreated: 'Conta criada!',
        checkEmail: 'Verifique o seu email para confirmar o registo.',
        errorCreatingAccount: 'Erro ao criar conta',
        errorSigningIn: 'Erro ao fazer login',
        errorGoogleSignIn: 'Erro ao fazer login com Google',
        terms: 'Ao criar uma conta, concorda com os nossos Termos de Serviço e Política de Privacidade',
      },
    settings: {
      title: 'Definições',
      profile: 'Perfil',
      email: 'Email',
      emailNote: 'O email não pode ser alterado',
      fullName: 'Nome Completo',
      fullNamePlaceholder: 'João Silva',
      company: 'Nome da Empresa',
      companyPlaceholder: 'Minha Empresa Lda',
      save: 'Guardar Alterações',
      saving: 'A guardar...',
      plan: 'Plano e Faturação',
      current: 'Atual',
      upgrade: 'Fazer Upgrade',
      trialActive: 'Teste ativo',
      endsOn: 'Termina em',
      processing: 'A processar...',
      subscriptionActive: 'Subscrição Ativa',
      renewsOn: 'Renova em',
      manageSubscription: 'Gerir Subscrição',
      integrations: 'Integrações',
      facebookAds: 'Facebook Ads',
      facebookDesc: 'Importe campanhas automaticamente',
      shopify: 'Shopify',
      shopifyDesc: 'Sincronize produtos e vendas da sua loja',
      connected: 'Ligado',
      disconnect: 'Desligar',
      connect: 'Ligar',
      loading: 'A carregar definições...',
      success: 'Sucesso',
      error: 'Erro',
      profileUpdated: 'As alterações foram guardadas com sucesso.',
      integrationsPage: {
        title: 'Integrações',
        subtitle: 'Gerencie as suas conexões com plataformas externas',
        summary: 'Resumo',
        activeIntegrations: 'integração ativa',
        activeIntegrationsPlural: 'integrações ativas',
        facebookAdsTitle: 'Facebook Ads',
        facebookAdsDesc: 'Gestão de campanhas publicitárias',
        shopifyTitle: 'Shopify',
        shopifyDesc: 'Sincronização de produtos e vendas',
        addStore: 'Adicionar Loja',
        noStores: 'Nenhuma loja Shopify conectada',
        connectFirstStore: 'Conectar Primeira Loja',
        connectedOn: 'Conectado em:',
        expiresOn: 'Expira em:',
        store: 'Loja',
        sync: 'Sincronizar',
        syncing: 'Sincronizando...',
        connected: 'Conectado',
        disconnected: 'Desconectado',
        expired: 'Expirado',
        connecting: 'A conectar...',
        connectFacebook: 'Conectar Facebook Ads',
        disconnect: 'Desconectar',
        syncStarted: 'Sincronização iniciada',
        syncStartedDesc: 'Os produtos estão a ser sincronizados em background',
        syncError: 'Erro na sincronização',
        disconnectSuccess: 'Desconectado com sucesso',
        connectSuccess: 'Conectado com sucesso',
        fillAllFields: 'Por favor, preencha todos os campos',
        facebookDisconnected: 'Facebook Ads desconectado',
        facebookError: 'Não foi possível desconectar o Facebook Ads',
        shopifyDisconnected: 'Loja Shopify desconectada',
        shopifyError: 'Não foi possível desconectar a loja',
        shopifyConnectError: 'Não foi possível conectar ao Shopify',
        storesUsage: 'Lojas',
        loginRequired: 'Por favor, faça login novamente',
      },
      plans: {
        beginner: {
          price: '€4.99/mês',
          annualOriginal: '59,88 €',
          annualPrice: '€44.91/ano',
          annualSavings: 'Poupe 14,97 €',
          features: ['ROAS Diário Básico', 'Sem automação']
        },
        basic: {
          price: '€14.99/mês',
          annualOriginal: '179,88 €',
          annualPrice: '€134.91/ano',
          annualSavings: 'Poupe 44,97 €',
          features: ['Daily ROAS Profit Sheet', '1 loja', '15 campanhas']
        },
        standard: {
          price: '€34.99/mês',
          annualOriginal: '419,88 €',
          annualPrice: '€314.91/ano',
          annualSavings: 'Poupe 104,97 €',
          features: ['Daily ROAS Profit Sheet', 'Campanhas', 'Cotação', '2 lojas', '40 campanhas']
        },
        expert: {
          price: '€49.99/mês',
          annualOriginal: '599,88 €',
          annualPrice: '€449.91/ano',
          annualSavings: 'Poupe 149,97 €',
          features: ['Daily ROAS Profit Sheet', 'Campanhas', 'Cotação', 'Product Research', '4 lojas', 'Campanhas ilimitadas']
        }
      },
      dangerZone: {
        title: 'Zona de Perigo',
        description: 'Ações irreversíveis que afetam permanentemente a sua conta.',
        deleteAccount: 'Deletar Conta',
        deleteDescription: 'Remove permanentemente a sua conta e todos os dados associados'
      },
      shopifyDialog: {
        title: 'Ligar Shopify',
        instructions: 'Para conectar sua loja Shopify, siga estes passos:',
        step1: 'Acesse o painel de administração da sua loja Shopify',
        step2: 'Navegue para: Settings (Definições) → Apps and sales channels (Apps e canais de vendas) → Develop apps (Desenvolver apps)',
        step3: 'Clique em "Create an app" (Criar app) e atribua um nome (ex: "Dashboard Integration")',
        step4: 'Clique em "Configure Admin API scopes" (Configurar âmbitos da Admin API)',
        step5: 'Selecione as seguintes permissões obrigatórias:',
        scope1: 'read_products - Para ler informações dos produtos',
        scope2: 'read_inventory - Para ler níveis de inventário',
        scope3: 'read_orders - Para ler informações de encomendas',
        scope4: 'write_products - Para atualizar produtos (opcional)',
        step6: 'Clique em "Save" (Guardar) para salvar as permissões',
        step7: 'Clique em "Install app" (Instalar app) para gerar o token',
        step8: 'Copie o "Admin API access token" que começa com "shpat_"',
        step9: 'Cole o token no campo abaixo juntamente com o URL da sua loja',
        required: 'obrigatório',
        recommended: 'recomendado',
        optional: 'opcional',
        openAdmin: 'Abrir Shopify Admin',
        storeName: 'URL da Loja Shopify',
        storeNamePlaceholder: 'minha-loja.myshopify.com',
        storeNameHelp: 'Cole o URL da sua loja (ex: minha-loja.myshopify.com ou minha-loja.com)',
        accessToken: 'Admin API Access Token',
        accessTokenPlaceholder: 'shpat_xxxxxxxxxxxxxxxxxxxxxxxx',
        accessTokenHelp: 'Token que obteve ao instalar o app (começa com shpat_)',
        cancel: 'Cancelar',
        connecting: 'A ligar...',
        connect: 'Ligar Loja',
        importantNote: 'Importante:',
        noteText: 'O token Admin API só é mostrado uma vez. Copie-o imediatamente após a instalação.',
        securityNote: 'Segurança:',
        securityText: 'Nunca partilhe este token. Ele dá acesso completo à sua loja Shopify.'
      },
      facebookWarning: {
        title: 'Requisitos para conectar Facebook Ads',
        description: 'Antes de prosseguir, certifique-se de que cumpre todos os requisitos necessários para estabelecer a conexão.',
        requirements: 'O que precisa:',
        requirement1: 'Uma conta Facebook Business Manager ativa',
        requirement2: 'Acesso ao Facebook Ads Manager com permissões de administrador',
        requirement3: 'Campanhas ativas ou historial de anúncios na sua conta',
        note: 'Se não tiver uma conta Business ou acesso ao Ads Manager, não poderá completar esta integração.',
        cancel: 'Cancelar',
        proceed: 'Continuar e Conectar'
      },
      userNotAuthenticated: 'Utilizador não autenticado',
      facebookConnectionError: 'Erro ao iniciar conexão com Facebook',
      trialExpiredTitle: 'Trial Expirado',
      trialExpiredMessage: 'O seu período de trial terminou em {{date}}. Está agora no plano FREE com funcionalidades limitadas. Faça upgrade para continuar com acesso completo.',
      fillAllFields: 'Preencha todos os campos.',
      integrationRemoved: 'Integração removida',
      shopifyDisconnected: 'Shopify desconectado e todos os produtos foram removidos.',
      facebookDisconnected: 'Facebook Ads foi desconectado.',
      errorConnecting: 'Erro ao conectar',
      checkCredentials: 'Verifique suas credenciais',
      shopifyConnected: 'Shopify conectado!',
      newStoreConnected: 'Nova loja "{{storeName}}" conectada! Os produtos da loja anterior foram removidos. Sincronize para carregar os produtos desta loja.',
      storeConnectedSuccess: 'Loja "{{storeName}}" conectada com sucesso.',
      errorSyncing: 'Erro na sincronização',
      tryAgain: 'Tente novamente',
      productsSynced: 'Produtos sincronizados!',
      syncStats: '{{created}} novos, {{updated}} atualizados de {{total}} produtos',
      errorLoadingProducts: 'Erro ao carregar produtos',
      insufficientShopifyPermissions: 'Permissões insuficientes no Shopify',
      shopifyPermissionsDesc: 'O Admin API token precisa das seguintes permissões: 1) Vá ao Shopify Admin → Settings → Apps and sales channels → Develop apps. 2) Selecione a sua app ou crie uma. 3) Em \'Admin API access scopes\', ative: read_products, read_orders, write_webhooks. 4) Instale/reinstale a app para gerar novo token. 5) Copie o novo Admin API access token. 6) Reconecte o Shopify nas Definições.',
      syncStarted: 'Sincronização iniciada!',
      syncStartedDesc: 'Os produtos estão a ser sincronizados em background. Recarregue a página em alguns segundos para ver os resultados.',
      listUpdated: 'Lista atualizada',
      productsSyncedSuccess: 'Produtos sincronizados com sucesso',
      syncFailed: 'Falha ao conectar com o Shopify. Verifique a sua ligação à internet.',
      unknownError: 'Erro desconhecido',
      invalidValue: 'Valor inválido',
      enterValidNumber: 'Por favor, insira um valor numérico válido',
      errorUpdatingQuote: 'Erro ao atualizar cotação',
      quoteUpdated: 'Cotação atualizada',
      quoteUpdatedDesc: 'Preço de fornecedor e Daily ROAS atualizados com sucesso',
      errorUpdatingQuoteDesc: 'Falha ao atualizar a cotação',
      errorLoadingData: 'Erro ao carregar dados',
    },
    billing: {
      title: 'Escolha o Seu Plano',
      subtitle: 'Gerencie suas campanhas de Facebook Ads com inteligência e simplicidade',
      monthly: 'Mensal',
      annual: 'Anual',
      perMonth: 'mês',
      perYear: 'ano',
      currentSubscription: 'Assinatura Atual',
      plan: 'Plano',
      manageBilling: 'Gerir Faturação',
      mostPopular: 'Mais Popular',
      unlimitedStores: 'lojas ilimitadas',
      stores: 'lojas',
      unlimitedCampaigns: 'campanhas ilimitadas',
      campaigns: 'campanhas',
      currentPlan: 'Plano Atual',
      choosePlan: 'Escolher Plano',
      checkoutError: 'Não foi possível iniciar o checkout. Tente novamente.',
      portalError: 'Não foi possível abrir o portal de faturação.',
    },
    contactBusiness: {
      back: 'Voltar',
      title: 'Solicite o seu Plano Business',
      subtitle: 'Preencha o formulário abaixo e a nossa equipa entrará em contacto em 24 horas para criar uma solução personalizada para o seu negócio.',
      whyBusiness: 'Porque escolher o Plano Business?',
      benefit1Title: 'Suporte Dedicado 24/7',
      benefit1Desc: 'Equipa dedicada disponível a qualquer momento',
      benefit2Title: 'Onboarding Personalizado',
      benefit2Desc: 'Configuração e treino customizado para a sua empresa',
      benefit3Title: 'Funcionalidades Sob Medida',
      benefit3Desc: 'Desenvolvemos features específicas para as suas necessidades',
      benefit4Title: 'Integrações Custom',
      benefit4Desc: 'Conectamos com as ferramentas que já usa',
      contactInfo: 'Informações de Contacto',
      availableAfterContact: 'Disponível após primeiro contacto',
      formTitle: 'Conte-nos sobre o seu negócio',
      name: 'Nome Completo',
      namePlaceholder: 'João Silva',
      email: 'Email Profissional',
      emailPlaceholder: 'joao@empresa.com',
      company: 'Empresa',
      companyPlaceholder: 'Nome da sua empresa',
      phone: 'Telefone',
      phonePlaceholder: '+351 912 345 678',
      website: 'Website',
      websitePlaceholder: 'https://www.suaempresa.com',
      numberOfStores: 'Número de Lojas',
      monthlyCampaigns: 'Campanhas Mensais',
      currentTools: 'Ferramentas Atuais',
      currentToolsPlaceholder: 'Ex: Google Analytics, Shopify, etc.',
      specificNeeds: 'Necessidades Específicas',
      specificNeedsPlaceholder: 'Ex: Relatórios customizados, integrações, etc.',
      message: 'Mensagem',
      messagePlaceholder: 'Conte-nos mais sobre o seu negócio e como podemos ajudar...',
      submit: 'Enviar Pedido',
      sending: 'A enviar...',
      responseTime: 'Responderemos em até 24 horas úteis',
      success: 'Pedido Enviado!',
      successDesc: 'Entraremos em contacto em breve para discutir a sua solução personalizada.',
      error: 'Erro ao Enviar',
      errorDesc: 'Ocorreu um erro. Por favor, tente novamente ou contacte-nos diretamente.',
    },
    notes: {
      loading: "Carregando blocos...",
      errorLoading: "Erro ao carregar",
      blockCreated: "Bloco criado",
      dragAndEdit: "Arraste e edite o bloco",
      error: "Erro",
      zoomIn: "Aumentar zoom",
      zoomOut: "Diminuir zoom",
      resetZoom: "Reiniciar zoom",
      createNew: "Criar novo bloco",
      colors: {
        yellow: "Amarelo",
        pink: "Rosa",
        green: "Verde",
        blue: "Azul",
        orange: "Laranja",
        purple: "Roxo",
        white: "Branco",
      },
      blockTypes: {
        postit: "Post-it",
        postitDesc: "Nota rápida com cor",
        checklist: "Checklist",
        checklistDesc: "Lista de tarefas",
        idea: "Ideia",
        ideaDesc: "Card de ideia com tags",
        file: "Ficheiro",
        fileDesc: "Upload de imagem/PDF",
        sketch: "Desenho",
        sketchDesc: "Desenho livre",
      },
      createBlock: "Criar novo bloco",
      postit: {
        placeholder: "Escreva a sua nota...",
      },
      checklist: {
        title: "Minhas Tarefas",
        addItem: "Adicionar item",
        itemPlaceholder: "Novo item...",
      },
      idea: {
        titlePlaceholder: "Título da ideia",
        descriptionPlaceholder: "Descreva a sua ideia...",
        tagsPlaceholder: "Tags (separar com vírgula)",
      },
      file: {
        upload: "Carregar ficheiro",
        uploading: "A carregar...",
        errorUpload: "Erro ao carregar ficheiro",
        fileUploaded: "Ficheiro carregado com sucesso",
        dragDrop: "Arraste o ficheiro aqui ou clique para carregar",
      },
      sketch: {
        draw: "Desenhar",
        erase: "Apagar",
        clear: "Limpar",
        color: "Cor",
        brushSize: "Tamanho do pincel",
      },
    },
  },
  en: {
    nav: {
      whatIsIt: 'What is it',
      features: 'Features',
      pricing: 'Pricing',
      faq: 'FAQ',
    },
    header: {
      login: 'Login',
      startFree: 'Start Free',
      getStarted: 'Get Started',
    },
    landing: {
      hero: {
        title1: 'Automate your',
        title2: 'Facebook Campaigns',
        subtitle: 'Your intelligent platform for automatic metric calculation and action recommendations.',
        benefit1: 'Automatically calculates metrics',
        benefit2: 'CPC, ROAS, CPA, Profit Margin in real time',
        benefit3: 'Smart recommendations: Stop, Scale, Maintain',
        ctaPrimary: 'Start Free for 10 Days',
        ctaSecondary: 'What Sheet Tools does for you',
      },
      features: {
        automation: {
          title: 'Complete Automation',
          description: 'Save hours of manual analysis with intelligent automation',
        },
        metrics: {
          title: 'Automatic Metrics',
          description: 'ROAS, CPC, CPA, CTR, Conversion Rate calculated automatically',
        },
        secure: {
          title: 'Secure Data',
          description: 'Secure connection via OAuth, your data always protected',
        },
      },
    },
    notes: {
      loading: "Loading notes...",
      errorLoading: "Error loading notes",
      blockCreated: "Block created",
      dragAndEdit: "Drag blocks and edit inline",
      error: "Error",
      zoomIn: "Zoom in",
      zoomOut: "Zoom out",
      resetZoom: "Reset zoom",
      createNew: "Create New",
      colors: {
        yellow: "Yellow",
        pink: "Pink",
        green: "Green",
        blue: "Blue",
        orange: "Orange",
        purple: "Purple",
        white: "White",
      },
      blockTypes: {
        postit: "Post-it",
        postitDesc: "Quick note with color",
        checklist: "Checklist",
        checklistDesc: "Task list",
        idea: "Idea",
        ideaDesc: "Idea card with tags",
        file: "File",
        fileDesc: "Image/PDF upload",
        sketch: "Sketch",
        sketchDesc: "Freehand drawing",
      },
      createBlock: "Create new block",
      postit: {
        placeholder: "Write your note...",
      },
      checklist: {
        title: "My Tasks",
        addItem: "Add item",
        itemPlaceholder: "New item...",
      },
      idea: {
        titlePlaceholder: "Idea title",
        descriptionPlaceholder: "Describe your idea...",
        tagsPlaceholder: "Tags (comma separated)",
      },
      file: {
        upload: "Upload file",
        uploading: "Uploading...",
        errorUpload: "Error uploading file",
        fileUploaded: "File uploaded successfully",
        dragDrop: "Drag file here or click to upload",
      },
      sketch: {
        draw: "Draw",
        erase: "Erase",
        clear: "Clear",
        color: "Color",
        brushSize: "Brush size",
      },
    },
  },
};
